### ISSUE TITLE
Submachine Gun Magazine 9mm & AP 

### ISSUE THREAD

**Issue by Herpederps** [BadDeathclaw/TG-Claw#1051]
The Submachine Gun Magazine 9mm and the AP variety aren't actually Magazine's but Ammo Boxes they in fact do have the sprite of the mags but the description says they're an Ammo box.
And you aren't able to put them in the 9mm Submachine gun.

AP's Description 
https://gyazo.com/b85e7f567a72e39018b7574cd12fab73
Regular Ammo Description 
https://gyazo.com/76216a2071147307601f7227732d1dcf

**Comment by Hekzder** [comment]
Don't think this is still a bug, AP mags may not be usable but I removed them a few patches ago regardless. Probably no longer relevant.
