### ISSUE TITLE
Solid beakers cant be made in the lath

### ISSUE THREAD

**Issue by billymom2** [BadDeathclaw/TG-Claw#1082]
Issue reported from  Round ID: 2136 (Bad Deathclaw TG Edition)

Reporting client version: 512

What happen was even with all the metal and glass i cant make any solid beakers someing might be broken i dont know

**Comment by SpaceVampire** [comment]
You were most likely using a lathe with DRM, because its counted as a sec item.

**Comment by Hekzder** [comment]
It is intended that you cannot produce solid beakers at a standard lathe.
