### ISSUE TITLE
Pacifist cannot fire beanbag round

### ISSUE THREAD

**Issue by robihunn** [BadDeathclaw/TG-Claw#1085]
[Priority]: # (Is it game breaking?)
Kinda for Pacifist players.
[Reproduction]: # (Explain your issue in detail, including the steps to reproduce it. Issues without proper reproduction steps or explanation are open to being ignored/closed by maintainers.)
Make a character with pacifist quirk -> Load caravan shotgun with beanbag slugs -> It will say "The caravan shotgun is lethally chambered! You don't want to risk harming anyone..." while beanbag is non-lethal

**Comment by ma44** [comment]
The beanbag does in fact deal five damage, therefore it's considered lethal.

**Comment by robihunn** [comment]
That was quick. I see. Thanks for the info.
