### ISSUE TITLE
Poultrice+Healing powder=Instant healing

### ISSUE THREAD

**Issue by MrBobCool** [BadDeathclaw/TG-Claw#1117]
[Priority]: Pretty high.

[PR]: # No idea.

[Reproduction]: # Try to fight someone with Poultrice and Healing powder or fight someone with Poultrice and Healing powder. Both being combined.

[Notes]: # It heals instantly, fix this before people abuse it heavily. I may just be one victim.

**Comment by RenGusta** [comment]
Try the same with Stims and Super Stims. Stacking meds is always a present issue. The fine line between useful but abusable and useless but abuseless is hard to maintain.

**Comment by MrBobCool** [comment]
> Try the same with Stims and Super Stims. Stacking meds is always a present issue. The fine line between useful but abusable and useless but abuseless is hard to maintain.

Yeah, either rules or something need to be changed or coders need to sweat off trying to patch this. It's extremely annoying. The only way to kill someone doing this is delimbing. Which uhh, if I remember is getting removed..

**Comment by RenGusta** [comment]
Incorrect! 

It's becoming not-RNG and having the general threshold raised. 

But yeah I'd like if stacked chems had a negative effect, like they slowly form a sedative or something.

**Comment by MrBobCool** [comment]
> Incorrect!
> 
> It's becoming not-RNG and having the general threshold raised.
> 
> But yeah I'd like if stacked chems had a negative effect, like they slowly form a sedative or something.

Ah I see. Well, better getyer sweatshop w-. Er, coders coding about it then.

**Comment by Hekzder** [comment]
Fixed via #1144.
