### ISSUE TITLE
High-Lethality is problematic

### ISSUE THREAD

**Issue by UndeadNappist** [BadDeathclaw/TG-Claw#1166]
Removing easy stuns and incapacitates mean everyone will resort to shooting each other.

This isn't necessarily all bad, as many people will use the cheap stuns into an simply methodology of murder, but having the ability to incapacitate/kidnap each other with relative ease prevents characters from being removed from the round if someone plans something.

Increasing the ability to act while in crit further exasperates this problem and makes it more likely for people to fight to the death.

Possible solution:
Increase amount of health available while unconscious
Make it so you heal while unconscious (at least, while sated, or perhaps other mechanics) and remove the O2 loss while unconscious (leaving bloodloss as a possible death)
Remove people's ability to tell whether you're dead or just unconscious, including the deathgasp thing unless they take the time to check your pulse ; deathgasp could be left in when leaving your last whisper or succumbing deliberately.

**Comment by RenGusta** [comment]
You know I actually like this, Hopefully someone starts pulling some ideas from this.
