### ISSUE TITLE
Protectron really powerful.

### ISSUE THREAD

**Issue by MrBobCool** [BadDeathclaw/TG-Claw#118]
[Priority]: # (Is it game breaking?)
Low, they run super fucking fast, do lots of melee damage, and have three burst lasers. So yeah, kind of.
[PR]: # (If you think you know the specific code / PR causing the problem then please do tell.)
Something to do with protectron stats and shit.
[Reproduction]: # (Explain your issue in detail, including the steps to reproduce it. Issues without proper reproduction steps or explanation are open to being ignored/closed by maintainers.)
Go to the hospital place above town, go to a protectron, die because of how hard it is to kill them and run away from them.
[For Admins]: # (Oddities induced by var-edits and other admin tools are not necessarily bugs. Verify that your issues occur under regular circumstances before reporting them.)
No admins did anything.
[Notes]: # (Other notes.)
I really would like this fixed.

**Comment by GhostEcho** [comment]
addressed by #168
