### ISSUE TITLE
Vault security bowman headset has no vault encryption key.

### ISSUE THREAD

**Issue by AndrewL97** [BadDeathclaw/TG-Claw#119]
[Priority]: # (Is it game breaking?)
Low
[PR]: # (If you think you know the specific code / PR causing the problem then please do tell.)
Headset/radio code
[Reproduction]: # (Explain your issue in detail, including the steps to reproduce it. Issues without proper reproduction steps or explanation are open to being ignored/closed by maintainers.)
On spawn
[For Admins]: # (Oddities induced by var-edits and other admin tools are not necessarily bugs. Verify that your issues occur under regular circumstances before reporting them.)

[Notes]: # (Other notes.)
 
![image](https://user-images.githubusercontent.com/22902112/47948394-2f75fb00-df7c-11e8-9ac0-6ca29bfee1a7.png)

**Comment by JohnBigless** [comment]
We could probably cheeze the bug by having Vault-Tec Security spawn with a Vault Encryption Key in their backpack.

**Comment by LetterN** [comment]
fixed(TM)

**Comment by SpaceVampire** [comment]
This still seems to be an issue
