### ISSUE TITLE
Security Camera Terminals don't work

### ISSUE THREAD

**Issue by AndrewL97** [BadDeathclaw/TG-Claw#120]
![image](https://user-images.githubusercontent.com/22902112/47948426-f1c5a200-df7c-11e8-9109-3fd87c617f9f.png)

**Comment by JohnBigless** [comment]
John here, apparently the reason why camera terminals don't work is because there **are no cameras in the vault.**

**Comment by LetterN** [comment]
Not a bug. There isn't any cameras in the vault
