### ISSUE TITLE
Crafting - Tear clothes into bandages

### ISSUE THREAD

**Issue by AndrewL97** [BadDeathclaw/TG-Claw#124]
Requires popup list to select what clothes to tear if more than one available (make this generic for all recipes, with handling to ignore duplicate stacks, reagents, etc.)

![image](https://user-images.githubusercontent.com/22902112/47948448-3a7d5b00-df7d-11e8-8cf0-b755cb3f5a11.png)

**Comment by LetterN** [comment]
#216

**Comment by roboticxlink** [comment]
I didn't make it have a popup or anything but I can work on that next. I just ported the old code in

**Comment by AndrewL97** [comment]
whatever works, I noticed that it doesn't seem to check bag/pocket contents, so its easily targeted at what you're holding, etc.
