### ISSUE TITLE
Crafting - Stimpacks

### ISSUE THREAD

**Issue by AndrewL97** [BadDeathclaw/TG-Claw#125]
![image](https://user-images.githubusercontent.com/22902112/47948460-6e588080-df7d-11e8-904b-b2cace93e931.png)

**Comment by UndeadNappist** [comment]
Recipe is in for stimpak fluid, based on the fallout 4 recipe. Could use a crafting recipe separate from the chemical one.
https://github.com/BadDeathclaw/TG-Claw/blob/21024cb3f8b4fb1b02d9f10dd10cc78bc594546a/code/modules/reagents/chemistry/recipes/medicine.dm#L256
