### ISSUE TITLE
Legion scout has the wrong backpack ammo.

### ISSUE THREAD

**Issue by MemedHams** [BadDeathclaw/TG-Claw#1269]
[Priority]: 
Moderate.

[PR]:

https://github.com/BadDeathclaw/TG-Claw/pull/163

This PR "fixed" the scout having no ammo but gave them the wrong type.

[Reproduction]: 
Spawn in as legion scout, check backpack.

The Legion scout has 7.62 stripper clip ammo when their gun, the scoped cowboy repeater, takes .308 rounds. This seems like a fairly simple fix but the issue delegates scouts to giving up their scope and taking another weapon if they want sustainable fire.

**Comment by TMR-SS13** [comment]
The Legion Scout starts with a .308 Scoped Hunting Rifle. The Scoped Hunting Rifle actually takes 7.62 ammo, though it is weaker then the .308. It's the same dynamic as the Explorer, just with the hunting rifle instead of the Rangemaster.

This isn't an issue.
