### ISSUE TITLE
Lockers, chests etc. not grabbing items on map init

### ISSUE THREAD

**Issue by AndrewL97** [BadDeathclaw/TG-Claw#130]
![image](https://user-images.githubusercontent.com/22902112/47948499-18380d00-df7e-11e8-97b7-dcd606bdc136.png)

**Comment by LetterN** [comment]
_how the fuck is this possible_

**Comment by AndrewL97** [comment]
haven't investigated this yet, but poking around the map recently

manually placed items seem to locker okay, its just the random spawners
I dare say that they fire after the locker grabbing.
Can probably fix by having them check if they are inside something, rather than just dropping on turf
