### ISSUE TITLE
Problem with Luxury shelter capsule

### ISSUE THREAD

**Issue by Stalkeros2** [BadDeathclaw/TG-Claw#138]
[Priority]: # Sorta game-crashing

[PR]: # idk

[Reproduction]: # 1. Buy luxury shelter capsule
2. Place it
3. Get crash, because of  showcase display thing loading its sprite

[For Admins]: # I think this happens because of that display case, it has no sprite after placing the capsule, and after crash it appears to have one

[Notes]: # pls don't remove simple capsules, they're pretty useful (if you don't shit with them)

**Comment by AndrewL97** [comment]
Thanks for letting us know, we will remove the capsules

**Comment by LetterN** [comment]
got any runtime logs? or anyone can test this and gib me runtime logs

**Comment by Stalkeros2** [comment]
Anyone can do this, those capsules cost like 3k in the vendor

**Comment by ma44** [comment]
This is getting removed from the vendor as of #135

**Comment by AndrewL97** [comment]
@ma44  is this resolved now?

**Comment by ma44** [comment]
@AndrewL97 is resolved
