### ISSUE TITLE
Energy weapons not accepting cells correctly - once removed, cells don't go back in

### ISSUE THREAD

**Issue by MrBobCool** [BadDeathclaw/TG-Claw#144]
[Priority]: # High

[Reproduction]: # Basically, press Z on any energy weapon like a disabler, taser, advanced energy gun, the bluespace chaos gun thing. Pulls a cell out, can't replace the cell. Making the gun unusable. 

[For Admins]: # I honestly don't know. Thing happened just by pressing Z, happens with default TG code guns most of the time.

[Notes]: # I friken hate spending resources on a gun to accidently press Z and then not be able to use it.

**Comment by JohnBigless** [comment]
This also happens with _Plasma Cutters_ and _Advanced Plasma Cutters_
Once the cell is removed, the gun no longer accepts plasma.

**Comment by GhostEcho** [comment]
Addressed by #387
