### ISSUE TITLE
Vault Door has no Walls Under It

### ISSUE THREAD

**Issue by WallaceShark** [BadDeathclaw/TG-Claw#146]
[Priority]: High

[Reproduction]: Right click under the Vault Door on any given round. It will have Vault Floors underneath, allowing one to walk past the door whether it is open or not.

[Notes]: The current Vault Door sprite is short enough that it doesn't cover the entire turf. One can easilly place new walls underneath the vault door now, making repairs more convenient than oldcode. Do keep this if possible.

**Comment by LetterN** [comment]
this is already fixed with one of the map edits that i did
