### ISSUE TITLE
Mine Floors/ Desert cannot be dug up. Glass is now rarer than Diamonds.

### ISSUE THREAD

**Issue by WallaceShark** [BadDeathclaw/TG-Claw#147]
[Priority]: Medium. Affects late round when glass reserves run low.

[Reproduction]: Take a pick/shove/etc. Click a ground turf. Sand does not come out. No sand means no smelting glass. Whatever stores you start with must last till the end of the round.

[Notes]: The Vault's mine has a mapping bug where tiles surrounding the mining base have Lavaland floor turf. While this is a known bug, it is also the only source of Sand within the entire map, and thus the only source of raw glass.

**Comment by LetterN** [comment]
about to be less rare soon (TM) #284
