### ISSUE TITLE
My scope mode is fucked

### ISSUE THREAD

**Issue by Djorgomush** [BadDeathclaw/TG-Claw#1478]
So, basically, my scoped weapons don't work as they are suppposed to work. In zoom mode of any scoped weapon, I am only shown a bit of area ahead of me, and I can't even see my character nor the interface on the screen. The only way to escape that mode is to drop the gun/binoculars. How can I fix that?

Issue reported from  Round ID: 2825 (Drymouth Gulch)

Reporting client version: 512

**Comment by RenGusta** [comment]
it's a screen size thing. Scopes don't behave unless you're on stretch to fit, in sizing of your screen.

**Comment by AndrewL97** [comment]
BYOND has a fullscreen mode that we can force through code, so surely there is a way to force stretch fit mode too... ill investigate when I have the chance @RenGusta
