### ISSUE TITLE
Wires Missing in Various Parts of the Vault

### ISSUE THREAD

**Issue by WallaceShark** [BadDeathclaw/TG-Claw#148]
[Priority]: Low

[Reproduction]: Crowbar open tiles in the displayed areas. Wires won't be there. Three spots are missing wires; 

>A tile under a Medical airlock powering Surgery
>A tile under the Evac airlock that powers Evac
>Several tiles under Mining that power the Elevator

[Notes]: Elevator wire is particularly bad, as it can leave mining crew trapped in the basement till someone above sends for rescue.

Below is a picture of the exact locations of each missing wire:
[https://i.imgur.com/lbFUbh5.png](url)

**Comment by WallaceShark** [comment]
Recent patches have fixed the missing wires in Mining. Medical and Evac still missing wires.

There's also a disposal pipe segment missing in Evac, same tile as the missing wire.

**Comment by LetterN** [comment]
about to be fixed in #284
