### ISSUE TITLE
Store walls missing textures for deconstruction stages

### ISSUE THREAD

**Issue by JohnBigless** [BadDeathclaw/TG-Claw#149]
Upon starting the deconstruction of a _store wall_ (cutting the outer grille), the wall's texture suddenly disappears.
Not even alt-clicking did the trick to be able to progress, because cone of vision.

**Comment by inkticious** [comment]
no idea if this was fixed yet or not, but if not i can do the sprites for it

**Comment by Kimochiiiiiiiiiiiiii** [comment]
3 months, that's how much it takes to save some icons from another code and paste it into BD
