### ISSUE TITLE
Placing floor tile on desert tiles gives a missing texture

### ISSUE THREAD

**Issue by JohnBigless** [BadDeathclaw/TG-Claw#150]
Simply placing a floor tile out of metal on a desert tile makes the purple & black missing texture checker board to appear.
Removing the checkerboard tile with a crowbar doesn't seem to have lingering effects, however.

**Comment by inkticious** [comment]
no idea if this has been fixed yet or not, but if not let me know and ill do the sprites for it

**Comment by UndeadNappist** [comment]
#237 just needs to be merged
