### ISSUE TITLE
Can't compile the .DME in Dreammaker

### ISSUE THREAD

**Issue by n3tis** [BadDeathclaw/TG-Claw#1507]
Extracted TG-Claw-master,
then opened it,
then opened .DME
and got these 3 errors
and I couldn't get a compiled .DMB to host a server (privately) with my friends.

code\__HELPERS\_lists.dm:510:error: #error Remie said that lummox was adding a way to get a lists
code\__HELPERS\_lists.dm:511:error: #error contents via list.values, if that is true remove this
code\__HELPERS\_lists.dm:512:error: #error otherwise, update the version and bug lummox

**Comment by waterwater1212** [comment]
due to 513 i think bro

**Comment by ProfessorPopoff** [comment]
Yeah. It's due to 513.
