### ISSUE TITLE
Braindeads, play dead. (Braindeads should lay down.)

### ISSUE THREAD

**Issue by MrBobCool** [BadDeathclaw/TG-Claw#151]
Alright so, I thought of this idea when I got banned for killing a braindead in a raid against the legion. I was going full throttle when I attacked (and killed) a legion standing up. Thinking he was a normal legion and not dead. I just killed him without thought. I soon later got banned for killing a braindead and as such, I want to prevent this by suggesting a feature where braindeads should lay down when brain dead. Simple feature, I don't think it would require much coding. Just something I thought so I wouldn't nor anyone else would get banned for doing such as I did or having a similar situation.

Plus. If they're REALLY braindead, they shouldn't have any motor skills.

**Comment by AndrewL97** [comment]
Had a look through on how other servers have handled this. Apparently this opens a can of worms with npc checking, simple mobs, etc.
at the moment this isn't horribly vital, but will still accept a PR from anyone else who wants to tackle the spaghetti.
