### ISSUE TITLE
Decal/Junk cleaner

### ISSUE THREAD

**Issue by AndrewL97** [BadDeathclaw/TG-Claw#156]
#### Issue
By 10 minutes into the round, there are dead mobs/players everywhere, spent casings that won't be picked up, blood trails everywhere, etc.

The level is excessive, and looks ridiculous. 

#### decay component:

type 	 - Decal,casing,corpse, etc. this is the category
age  	 - The age since the mob obj was added to the ticker
decayMax - When age reaches this, the obj is removed from the ticker
deleteOnDecay - If this obj gets deleted on remove (i.e delete bullet casings, but leave rotted player)

2 solutions proposed:

#### Time based cleanup

Use the age/decay/deleteondecay vars in above component to gradually cleanup after a certain time
decay allows things like blood being replaced with dried blood, corpse decay, food decay, etc.

#### count based cleanup

Categories have a max cap, as items get added to the category lists, the oldest objects get deleted
first in first out style

another possibility
rain, to act as a cleaner to wipe everything at once @roboticxlink

**Comment by UndeadNappist** [comment]
Rain with sterilizine or space cleaner could work.
