### ISSUE TITLE
Observers can't respawn ever

### ISSUE THREAD

**Issue by AndrewL97** [BadDeathclaw/TG-Claw#160]
[Priority]: # (Is it game breaking?)
High
[PR]: # (If you think you know the specific code / PR causing the problem then please do tell.)
#159
[Reproduction]: # (Explain your issue in detail, including the steps to reproduce it. Issues without proper reproduction steps or explanation are open to being ignored/closed by maintainers.)
Observe, try to respawn

[For Admins]: # (Oddities induced by var-edits and other admin tools are not necessarily bugs. Verify that your issues occur under regular circumstances before reporting them.)
Issue occurs due to no mind assigned to observers, so causing runtimes in check

[Notes]: # (Other notes.)

**Comment by rhicora** [comment]
Observers can see and click Respawn but it fails silently.

Note: this doesn't impact dead characters, who have a regular respawn timer and can click Respawn.
