### ISSUE TITLE
Legion Scouts Have No Ammo

### ISSUE THREAD

**Issue by MrBobCool** [BadDeathclaw/TG-Claw#164]
Low

I don't know if this would be a "bug" but if it was intended to be like this, please do let me know.

To find this "bug" spawn as a Legion Scout, they have no ammo for their gun.

[Notes]: # (Other notes.)
Like I said, tell me if this was intended or not.

**Comment by rhicora** [comment]
![image](https://user-images.githubusercontent.com/37093159/48295156-21255480-e43e-11e8-916d-06ed7a068d91.png)

@MrBobCool Do they have ammo for another gun?

**Comment by MrBobCool** [comment]
No.

**Comment by AndrewL97** [comment]
#163 has been merged
