### ISSUE TITLE
BOS mechs/armor change/nerf

### ISSUE THREAD

**Issue by genarall1** [BadDeathclaw/TG-Claw#165]
Been playing on server as BOS for a while. Noticed that with what we have, with enough materials we can basically steamroll over everyone with the powerhouses that are mechs. Instead of being able to make mechs, I propose we instead be able to make our own power armor up to the t-51b with enough research in sci. Fits in with the BOS fixing/making their own power armor in the games plus doesn't make us too overpowered unlike with mechs.

**Comment by MrBobCool** [comment]
Mechs are basically "power armor". I suppose that maybe they should just change the name of the mechs and maybe nerf them a slight bit.
