### ISSUE TITLE
Missing waste plants from legacy - needed for stims + broc, misc crafting

### ISSUE THREAD

**Issue by AndrewL97** [BadDeathclaw/TG-Claw#174]

**Comment by roboticxlink** [comment]
PR #216 adds broc and xander plants, seeds, fruit/flower. As well as crating 'healing powder'. Also adds crafting metal armors and deconstructing 'under' clothes into cloth. Stims soon, I think nappist was doing that. I just wanted to rush broc and xander in.

**Comment by UndeadNappist** [comment]
#217 recipe is blood and spacecillian

**Comment by LetterN** [comment]
#216
