### ISSUE TITLE
Poofing wood stacks

### ISSUE THREAD

**Issue by roboticxlink** [BadDeathclaw/TG-Claw#175]
When adding a stack of wood (possibly other materials as well) to your bag, that already has a stack of them in your bag, the entire stack you added disappears into the void...

**Comment by WallaceShark** [comment]
Not a bug. Stacks of the same material now combine automatically when placed in the same container. This is intended to save space by having one small stack of 10 material, as opposed to two small stacks of 5.

You can also see this happen when placing two of the same material on a single tile.

Examine the stacks to see how many planks are in each before one 'dissapears', then examine them after. You'll find they have combined into one.

**Comment by roboticxlink** [comment]
No I know that. I was dealing with stacks of 50, and placed another stack of 50, and it ate them all. I had 200 stacks of wood then dropped down to 100 or 50 because of it.
