### ISSUE TITLE
Bonfire Smelting Bug

### ISSUE THREAD

**Issue by roboticxlink** [BadDeathclaw/TG-Claw#184]
Issue: Ore disappears when you throw it past a bonfire onto a wall.

Expected: ore would hit the wall, land in the fire, tribal smelt. 

Recreate: build a bonfire next to a wall. Acquire ore. Throw the ore at the wall behind the fire. Watch it disappear. (issue was noticed with uranium ore). 

Temporary fix: throwing the ore directly on the fire will land it, and smelt it as intended. So don't expect walls to stop it because they will eat your ore slag.

Things i didn't test: if it disappears on hitting any wall. Which types of walls (lost ore in the vein cave by metarush mining, and the dark cave walls as well). If it disappears upon passing over a fire but not in it.

Priority: low because no one knows how to ghetto smelt and it's not game ending.

**Comment by AndrewL97** [comment]
I didn't know you could smelt with bonfires, thats pretty neat
