### ISSUE TITLE
Roles Spawning With Survival Box

### ISSUE THREAD

**Issue by roboticxlink** [BadDeathclaw/TG-Claw#185]
I've noticed a couple roles spawning with the standard box of mask, tank, and epi injector. Since not every role spawns with it, I believe this is not as intended.

Currently noticed roles are: pusher, certain legion follower sub roles. 

I can try to take out the box in default starting inventory (that these roles must be defaulting to). I just wanted to make sure this wasn't intended.

**Comment by AndrewL97** [comment]
Not intended, feel free to fix!

**Comment by GhostEcho** [comment]
I haven't seen any of these boxes spawning

**Comment by GhostEcho** [comment]
Taking a run through all the roles, it seems only Vault Engi, Sec and Chief of Security spawn with mask, tank and epi pen, any other job that spawns with a survival box gets a bandana, stimpack, radaway gauze and flare
