### ISSUE TITLE
Feature Request: Periodic Rain

### ISSUE THREAD

**Issue by roboticxlink** [BadDeathclaw/TG-Claw#187]
Tech Priest (discord) had an idea for something to periodically wipe all the blood/gore from the map to help with the lag.

I thought of some sort of rain cycle, passing over the map like the day/night cycle, that would clear all the blood and douse fires, maybe gets people wet like showering. 

How badly would such a system itself lag the server? 

Would this be a viable solution/feature to fix the persistent mess all over the wasteland?

**Comment by roboticxlink** [comment]
"Cleaner 'nade" raindrops?

**Comment by LetterN** [comment]
basically duplicate of #156

**Comment by roboticxlink** [comment]
I'll just close it then make it more compact. Didn't see that issue. Thanks.
