### ISSUE TITLE
Making a Full Mech Loading Glitch.

### ISSUE THREAD

**Issue by MrBobCool** [BadDeathclaw/TG-Claw#189]
Issue reported from  Round ID: 130

Reporting client version: 512

Alright, so. When you're making a **full mech from the exosuit fabricator, when it pops out (almost instantly) it will continue to say please wait till process is complete** (or blah blah blah.) Don't know what caused this. I would like this fixed _instead of having to deconstruct the thing every time._

Seems science is fucked on many things at the moment.

**Comment by ma44** [comment]
Forgot about this bug; actually was a anti href spoofy thingy and was fixed back in legacy.
