### ISSUE TITLE
Destroying objects that qdel with projectiles

### ISSUE THREAD

**Issue by UndeadNappist** [BadDeathclaw/TG-Claw#194]
[Priority]: # Causes runtimes.

[Reproduction]: # Destroy anything that qdels with a projectile weapon - window, wood door, etc. Tested it on several.

[Message]:
[23:23:47] Runtime in unsorted.dm,1228: The window taking damage after deletion
  proc name: stack trace (/datum/proc/stack_trace)
  src: the window (/obj/structure/window/fulltile/wood_window)
  src.loc: null
  call stack:
  the window (/obj/structure/window/fulltile/wood_window): stack trace("The window taking damage after...")
  the window (/obj/structure/window/fulltile/wood_window): take damage(25, "brute", "bullet", 0, 8, 0)
  the window (/obj/structure/window/fulltile/wood_window): take damage(25, "brute", "bullet", 0, 8, 0)
  the window (/obj/structure/window/fulltile/wood_window): bullet act(the bullet (/obj/item/projectile/bullet/softbullet), "l_arm")
  the bullet (/obj/item/projectile/bullet/softbullet): Collide(the window (/obj/structure/window/fulltile/wood_window))
  the bullet (/obj/item/projectile/bullet/softbullet): pixel move(1, 1, 0)
  the bullet (/obj/item/projectile/bullet/softbullet): process(1)
  Projectiles (/datum/controller/subsystem/processing/projectiles): fire(0)
  Projectiles (/datum/controller/subsystem/processing/projectiles): ignite(0)
  Master (/datum/controller/master): RunQueue()
  Master (/datum/controller/master): Loop()
  Master (/datum/controller/master): StartProcessing(0)

**Comment by LetterN** [comment]
probably when 2 people is shooting at it and it got qdel'd but it got shot at the same time, technically not a bug

**Comment by UndeadNappist** [comment]
No, this was on my private test server, when I was alone and no other players logged on.

It was from single bullets.
