### ISSUE TITLE
Security Radios Should Have Vault Frequency. (Request)

### ISSUE THREAD

**Issue by MrBobCool** [BadDeathclaw/TG-Claw#208]
Alright so, if you join as a Vault Security. Your radio ONLY has the security channel. Now, as much as I would love to not hear the total chaos on the vault frequency. I'd like it so I could hear what the fuck is happening. So it's simple, **add the vault frequency/channel to the starting security guards radio.** Hopefully this will be added soon.

**Comment by AndrewL97** [comment]
#119
