### ISSUE TITLE
Part issues with Machines

### ISSUE THREAD

**Issue by Monika4** [BadDeathclaw/TG-Claw#210]
[Priority]: # Quite Bad

[PR]: # (If you think you know the specific code / PR causing the problem then please do tell.)

[Reproduction]: # (Explain your issue in detail, including the steps to reproduce it. Issues without proper reproduction steps or explanation are open to being ignored/closed by maintainers.)
To break a Sleeper just upgrade the part pass the Nano-manip and it only allows for Basic Chemicals. To break a cloning you just upgrade the parts once more past Nano-manip and Cloning is quite bad as you can spawn with out organs and limbs because it goes so fast

[For Admins]: # (Oddities induced by var-edits and other admin tools are not necessarily bugs. Verify that your issues occur under regular circumstances before reporting them.)

[Notes]: # (Other notes.)
this is quite game breaking as I think the part effectiveness has been pushed quite far and in turn has broken some machines e.g. Sleeper, Cloner,

**Comment by AndrewL97** [comment]
fixed in next patch
thanks @Monika4
