### ISSUE TITLE
Request : Changing UnStable Mutatage to FEV or Force Ev Virus 

### ISSUE THREAD

**Issue by Monika4** [BadDeathclaw/TG-Claw#220]
Feature requests are somewhat handled in the repository. The best place to discuss these ideas would be on the discord: https://discord.gg/pY33Q8c
This would make Sense both in Lore and Gameplay as it would give Reason to stay clear and would add a RP level to it. I dont Mean make a new chem, just mean changing the name of it

**Comment by UndeadNappist** [comment]
Easy as going in and changing the chem name and description with a mass find + replace in atmo or the like. See https://github.com/rhicora/TG-Claw/blob/master/contributing.md

**Comment by GhostEcho** [comment]
Can be closed just a reminder
