### ISSUE TITLE
Security lockers in the Vault Brig do not spawn

### ISSUE THREAD

**Issue by JohnBigless** [BadDeathclaw/TG-Claw#223]
While browsing trough the map files, i noticed there are two lockers in the brig that do not seem to spawn at all when the game starts.
![brig lockers](https://user-images.githubusercontent.com/44721288/48900686-5fb20a80-ee53-11e8-8f69-68e2658cc53d.png)

**Comment by LetterN** [comment]
They're security pop-based lockers.
