### ISSUE TITLE
A bit more of mining items-related stuff.

### ISSUE THREAD

**Issue by Stalkeros2** [BadDeathclaw/TG-Claw#233]
(Should've done this one with suit issue, probably)

Make explorer suit be able to carry guns and ammo like any other armor, without restricting it to carry mining equpment.

Fix "breaking" (being not able to stuff cell back inside) of mining guns (KA, both cutters) after taking their cell out, and, as i remember, cutter will lose their sprite after taking the cell out.

Crusher should mark people (probably), but, to make it balanced, add field removing by clicking on it/resisting.

Allow explorer's webbing to carry ammo (only mags) and various small items like food, cigars, money, etc.

Removing hair after puting explorer hood on.

A way to get sand via mines.

**Comment by UndeadNappist** [comment]
Denied for powergame reasons. Explorer suit is likely to get hit by more nerfs.
