### ISSUE TITLE
Buttons in Vault Enterance don't work

### ISSUE THREAD

**Issue by JohnBigless** [BadDeathclaw/TG-Claw#238]
The button in the Vault Enterance Checkpoint doesn't work. It is supposed to open/close the blast doors near the vault door.

**Comment by UndeadNappist** [comment]
Mapping issue. They're /obj/machinery/button instead of /obj/machinery/button/door

**Comment by roboticxlink** [comment]
@AndrewL97 this can be closed. Fix was merged with #177
