### ISSUE TITLE
Shotgun drum magazine shenanigans

### ISSUE THREAD

**Issue by JohnBigless** [BadDeathclaw/TG-Claw#239]
Rubber Shot drum magazines are loaded with Beanbag Slug Shells when printed.
Beanbag Slug drum magazines are loaded with Buckshot Slug Shells when printed.

**Comment by LetterN** [comment]
kek
rubber shots are beanbag

**Comment by JohnBigless** [comment]
@LetterN
Wait, if the 8-round spready stamina dealing ammo is supposed to be beanbag, then what is rubber shot supposed to be?

**Comment by ma44** [comment]
@JohnBigless 
https://github.com/BadDeathclaw/TG-Claw/blob/master/code/modules/projectiles/boxes_magazines/external/shotgun.dm#L38
idk man they seem right

Rubbershot is the buckshot version of beanbags, close range stamina damage VS slug stamina damage

**Comment by GhostEcho** [comment]
Rubbershot spawns in beanbags, beanbag mags in spawn in buckshot, will take a look at tomorrow
