### ISSUE TITLE
Todo List: Mapping

### ISSUE THREAD

**Issue by UndeadNappist** [BadDeathclaw/TG-Claw#242]
Den:
Without changing Den size much;
Rework to be two main roads, no side roads, no wandering things. Put everything on the main roads.
Well in center of town, side platform area and chairs for town square meeting to right.
Add mayor, ~~sheriff, deputy,~~ and barber roles (one each).
Add mayor's house to top.
Sprite mayor's worn banner and clothes.
~~Sprite sheriff and deputy badges (reskinned IDs).~~ Apparently a lot of people hate the current sprites for 'em. Make gold and silver stars accordingly.
Add box of deputy badges to sheriff.
~~Expand bar and farm on left until it occupies entire corner.~~ 
Add ~~junkyard, includes scrap metal, autolathe,~~ recycler and junked cars.
Change hospital to barber's in front, tiny hospital in back (it doubles up).
~~Leave clear space down the road so people can build their own houses/shanties somewhere(?)
Try to force everyone to use the main road, not weird wandering paths, unless in shanty-town.~~

Dungeons (Enclave and various):
Make them more beatable without "cheesing" them (and remove the cheese), lower rewards, increase rewards as appropriate. Create hints and paths to get out there that people can find in game, including notes and the like off main roads even if they're tucked in corners of the map.

It might be a good idea to take away a lot of super gear at the end of dungeons. The point of dungeons in ss13 is to give people with guns something to shoot at. If they clear the dangerous dungeons, and you give them even MORE powerful guns, they want to use them. That's a design flaw - they'll end up shooting people. Do we want that?
Maybe the rewards at the end of dungeons should be intriguing puzzles, complicated devices, or things that can influence the server as a whole in interesting ways and I realize this is exactly how goon does it;
With the starting "easiest" dungeon being the one that having a pile of equipment that gets you well suited up for the others, and the others just having fascinating but not game-breaking implements and tools.

NCR base:
~~Replace autolathe with constructionlathe.~~
~~Delete spare metal and glass~~
Add NCR radios to armory (? this might've been done already)
Rework ammunition and guns to be standard-issue and to have ammunition for the guns they already have. (In progress)
~~Add a photocopier
Add a fax machine
Add more damn pens
Put some offices down that get foot traffic and oversee things
Move them into a building that they've taken over near the road out of the area (why would they be right next to the enclave base, at the end of the road, near a bunch of ghouls...?)~~

Hospital:
Make it more dangerous or remove the medical equipment there
Add medicines scattered around that could be picked up.
Leave chemmaster, remove chemdispenser?

~~Gun store:
Remove the metal and glass stacks next to autolathe.
Replace autolathe with constructionlathe?
Add gutsies~~

Legion Base:
Remove a lot of guns and ammo.
Add a crap-ton more ~~spears, machetes, handcuffs,~~ uniforms, and ~~bolas.~~
-Maybe nerf spear damage in the future (pneumatic issue)

~~Raider/BoS base:
Up and move raider spawn away from BoS base, or move BoS somewhere better-hidden.~~

~~Klamat:
Add recycler/crusher
Add constructionlathe.~~

Entire Desert/farms:
~~Move brahmin away from monsters that kill them on roundstart, or the other way around.~~
Add more loot tables
Emphasize areas "themes" instead of they have loot because monsters.
Add loot spawns to ghouls that are just piles of clothing or random garbage to give the impression you're killing someone. Or just have the spawns appear under them, implying they tore their clothes off ;whatever.
~~Fix the fence facing the wrong way in the side farm near legion base~~

Powerplant/Sunnydale:
Amend sunnydale to use the powerplant for power, and not a magical SMES unit

Magical SMES unit area:
Get rid of it because it's nonsense
Force people to use reactors
Decrease amount of uranium you get out
Maybe improve how much power you get out of one uranium sheet?
Add irradiation to reactors

Research Machines/BoS:
Add data disks across the map
Remove data disk generation at all
Put the data disks in faction bases maybe?
Make them random loot drops so you can't just metagame, gate behind dungeons that you have to negotiate past people to get at
#348 just needs cleanup

~~Gutsies:
Change their melee attack to do fire damage and an appropriate flamethrower description, have it set people on fire~~

Radiation:
Add radiation to mapping in deathclaw den and radmines

Secret dungeons:
Move all the dungeons to their own separate map files unless we want them linked.

Feel free to comment or add thoughts.

**Comment by WallaceShark** [comment]
Legion Base:
Replace the eastern mountain area with water tiles. Make it look like the legion came from their seat of power on the other side of the Colorado River. Potentially stretch this water down the entire right side of the map to the mountains south of legion base; it would look really swell while still serving as a barrier.

Also, the vault buttons work in current release.

**Comment by UndeadNappist** [comment]
> Also, the vault buttons work in current release.
They don't. The blast shutters do not open when you press the nearby buttons.

**Comment by UndeadNappist** [comment]
>Emphasize areas "themes" instead of they have loot because monsters.
Piles of clothing and misc. gear you'd expect to see average settlers wear spawning under ghouls.
Fewer armor pieces in closets and more random clothes, hand labelers, pens, boots, boxes of stuff, and so on and so forth.
Wedding chapels and stuff.
Making homes seem like homes.
Adding more flavor stuff to places, like a bell to the hotel, stripper poles, or other 'eye candy' things or objects that really do very little.
More showers.

**Comment by UndeadNappist** [comment]
Cleanup to the todolist. Callout JTGSZ, Rhicora, and GhostEcho and there's likely other people I'm forgetting.
