### ISSUE TITLE
Proximity Sensor, Infrared Emitter, Voice Analyzer Bug

### ISSUE THREAD

**Issue by MrDbaggy** [BadDeathclaw/TG-Claw#243]
[Priority]: Not game breaking

[PR]: Don't know
[Reproduction]: So I've noticed when experimenting with explosives that Sensors and Emitters besides Voice Analyzer seem to the have the issue where they don't seem to trigger when armed. For instance by themselves they work partially fine the Sensor can sometimes be ran past without triggering if triggered earlier before. Same with the Emitter, but when attached to a Chemical Grenade they don't seem to work at all when armed. (They can be picked up when armed and moved around for a while before detonating) And the Voice Analyzer sometimes doesn't trigger when said call word is said not sure if walls have anything to do with it.

[For Admins]: Unsure

[Notes]: None

**Comment by UndeadNappist** [comment]
Proximity sensor to igniter works fine in a chemical grenade. Infrared emitters do act weird, however. Do some more testing.

**Comment by MrDbaggy** [comment]
Sure thing, will check tomorrow.

**Comment by GhostEcho** [comment]
Issue still exists, think it has to do something with infrared emitter being IN the grenade

**Comment by UndeadNappist** [comment]
Infrared emitters have a direction, I think is the issue. Grenades do not have a pointing direction.

**Comment by MrDbaggy** [comment]
In the video I wasn't using a infrared emitter I was using a proximity sensors with an igniter although infrared emitter and igniter behave the same way as the sensor.

**Comment by UndeadNappist** [comment]
Proximity sensors can do REALLY wacky stuff as it turns out, even when they "work." Staple "runtimes are a problem" to this.
