### ISSUE TITLE
New Coal Ore

### ISSUE THREAD

**Issue by AndrewL97** [BadDeathclaw/TG-Claw#246]
drops /ore/coke 

need to add to usual mining spawns + create sprite

**Comment by inkticious** [comment]
i can make the sprites for these, if you want

**Comment by UndeadNappist** [comment]
https://github.com/BadDeathclaw/TG-Claw/blob/d6ffeb207849abcc3d993d4326ee0cef6c9c1a73/code/game/objects/items/trash.dm#L74

**Comment by AndrewL97** [comment]
Hey Nappist,
this and the smelter tickets were all related to the offline crafting
project, probably fine to close these unless somebody else plans to work on
it.
Leo made all the sprites for it, in spriter private

**Comment by UndeadNappist** [comment]
Didn't even know they had sprites. Someone will get to it eventually.

**Comment by GoodG1448** [comment]
There is actually a sprite for it in mining icons. The thing is that it is a whole sprite with the rock and everything. I don't even know in which folder the iron/diamond/uranium/gold/silver/diamond overlays decals are to move it there.

![imagen](https://user-images.githubusercontent.com/38330373/53396231-ba8f5c80-3982-11e9-80ab-11e608ffc64a.png)
