### ISSUE TITLE
Attackby derived procs attempting to act after qdel

### ISSUE THREAD

**Issue by UndeadNappist** [BadDeathclaw/TG-Claw#251]
[Priority]: Spawns runtimes

[PR]: No idea. Probably points to several line of codes

[Reproduction]: Do anything with a mob attackby that causes a target to call on qdel(src) (e.g., be destroyed)

[Notes]: A more complete report of #194
Essentially when you attack with a weapon, it calls on several procs - damage, blood on your hands, or what have you. There seems to be an issue where when a weapon is used on something that is destroyed (windows, a gibbing body, and so forth) it attempts to call on the src for the proc to engage the weapon properly.
Unfortunately, it just deleted itself, so it runtimes.

![image](https://user-images.githubusercontent.com/7409796/52099166-e20f2700-2586-11e9-9ece-7ce62c7a0bf2.png)

**Comment by UndeadNappist** [comment]
![image](https://user-images.githubusercontent.com/7409796/52921092-28bf8980-32c8-11e9-9099-666774e04703.png)

**Comment by LetterN** [comment]
just add a `if(QDELETED(src)) return`

**Comment by LetterN** [comment]
![image](https://user-images.githubusercontent.com/24603524/57920077-c11bd900-78cc-11e9-8274-126e8f6411bc.png)
technicaly not a bug, due to the code just warns, not a runtime.
