### ISSUE TITLE
Pipe Rifles and Pipe Pistols spawning loaded with 10mm ammo.

### ISSUE THREAD

**Issue by JohnBigless** [BadDeathclaw/TG-Claw#255]
Apparently, Pipe Rifles/Pistols aren't supposed to take 10mm, but shotgun shells.
In that case, they should spawn with an Improvised Shotgun Shell loaded instead of 10mm.

**Comment by Garen7** [comment]
Are you sure its not the other way around? That they should be loaded with 10mm? A shotgun pistol kinda sounds janky.

**Comment by Garen7** [comment]
looking at the code 10mm seems like the intended ammo type

**Comment by roboticxlink** [comment]
I agree. I feel they're supposed to be wonky ass cheap guns made with duct tape. They should just be single loaded 10mm guns to help deal with early ghouls and piss porr varmint rifle weapons.

**Comment by EvenInDeathIStillServe** [comment]
How is this a bug? The intended ammo type is 10mm. Working as intended.
http://fallout.wikia.com/wiki/Zip_gun_(Fallout_2)

**Comment by GhostEcho** [comment]
I think the mag type is only for spawning with it, otherwise it's using shotgun as a parent for it's reloading

**Comment by UndeadNappist** [comment]
Fixed.
