### ISSUE TITLE
You can't carry weapons in the suit slot of explorer suit

### ISSUE THREAD

**Issue by Stalkeros2** [BadDeathclaw/TG-Claw#267]
[Priority]: # Low-medium, depends on the situation

[PR]: # no

[Reproduction]: # 1. Try to stuff some gun in the suit storage of explorer suit.
2. Don't succeed in it.
3. Be sad because you'll have to carry your KA with yourself again

[For Admins]: # idk
[Notes]: # Make it able to take only light-medium guns like Carbines, SMGs, shotguns and such (No heavy weapons like that big sniper rifle, gatling laser or, if you'll find some, rocket launcher)

**Comment by UndeadNappist** [comment]
I've been seriously considering making it so you can only carry smaller-type weapons and excluding carbines and shotguns entirely, and forcing people to wear both of those on the back slot.

A lot of them are missing back slot icon-states though.

**Comment by GhostEcho** [comment]
Ren doesn't want them to hold guns, issue can be closed

**Comment by Stalkeros2** [comment]
*sigh*
