### ISSUE TITLE
lazer weapon runtime due to null.charge

### ISSUE THREAD

**Issue by LetterN** [BadDeathclaw/TG-Claw#295]
![image](https://user-images.githubusercontent.com/24603524/50284190-322ca100-0493-11e9-89d9-a019275ce200.png)

**Comment by UndeadNappist** [comment]
Is apparently not fixed. @JTGSZ

**Comment by JTGSZ** [comment]
welp

**Comment by LetterN** [comment]
should not be an issue anymore(C)(TM)
