### ISSUE TITLE
Surgery Button and Power issues in Surgery

### ISSUE THREAD

**Issue by Monika4** [BadDeathclaw/TG-Claw#307]
Priority: # its annoying to wire surgery every round

PR: I think it is to with the same issue as the vault blast doors and window shutters but the wiring connecting surgery to the APC is broken

Reproduction: Use a T-ray scanner in medical in vault and you will see the broken wiring
[For Admins]: # (Oddities induced by var-edits and other admin tools are not necessarily bugs. Verify that your issues occur under regular circumstances before reporting them.)

[Notes]: # (Other notes.)

**Comment by Monika4** [comment]
Button in Surgery vault room broke as well

**Comment by UndeadNappist** [comment]
Cross-ref with #148

**Comment by GhostEcho** [comment]
fixed at some point in the recent mapping changes, not sure which PR https://imgur.com/a/CV90q1J

**Comment by JTGSZ** [comment]
I got it in map change PR.
