### ISSUE TITLE
new Examine Feature can now allow you to meta Gender

### ISSUE THREAD

**Issue by Monika4** [BadDeathclaw/TG-Claw#327]
Priority: # it can be used to meta game gender 

PR: # (If you think you know the specific code / PR causing the problem then please do tell.)

[Reproduction]: # examine other players with gender hiding equipment allows you to see their gender even if they are wearing Gender hiding gear and the char term is used is "they"

[For Admins]: # (Oddities induced by var-edits and other admin tools are not necessarily bugs. Verify that your issues occur under regular circumstances before reporting them.)

[Notes]: # (Other notes.)
![live test data](https://user-images.githubusercontent.com/45178482/50727188-5af99b00-110f-11e9-9ba5-dae0163db826.PNG)

**Comment by EvenInDeathIStillServe** [comment]
I'll try to take care of this this week.
