### ISSUE TITLE
Buff soap as a cleaning tool.

### ISSUE THREAD

**Issue by GoodG1448** [BadDeathclaw/TG-Claw#339]
Remove the progress bar when cleaning with soaps, make it clean tiles with a single click.

Soap is far less common than mops now since mops are craftable (I am aware that you can make soap using gibs and lye, but still, they are less common).
Mops are technically inferior since you can still slip people with water puddles. Space cleaner works but it is a pain in the ass to have to refill it and hardly anyone has a chem dispencer to do so. (And the fact that you have to find spray bottle to begin with.)

**Comment by Monika4** [comment]
Gibs are more common than breathable air

**Comment by Monika4** [comment]
yeah its a pain in the ass in the wastes when all you have is either a soap or a mop. rarely both

**Comment by Monika4** [comment]
well fun-fact as well here just gonna adds but still gonna change the soap but homemade soap is Slightly faster than mop

**Comment by Monika4** [comment]
PR merged :)
