### ISSUE TITLE
New trading role & mechanic

### ISSUE THREAD

**Issue by EvenInDeathIStillServe** [BadDeathclaw/TG-Claw#345]
This is a suggestion for a new role and mechanic.

**Trader**
-Spawns with a deployable trading console and a trading license item.
-Can use the console to order items. The console spits out a receipt. Trading console needs you to have a trading license to work.
-The receipt can be used at a trade post (undeground trade network, the trade post is the link between surface and the underground)
-Put in caps and an elevator brings up a crate with the ordered items.
-Trading post has a non-movable trading console for on-the-spot ordering. Still needs a trading license so random folks can't use it.
-You can sell items at the trade post but you need a trading license.

This should make the game have a more meaningful economy, and promote trade and setting up shops.
Also, I think the coin mint should be removed if this gets added.

**Comment by UndeadNappist** [comment]
Trading role is in jobs, it's just commented out for some reason. You can RP as a trader whenever you want, you don't need a special dispensation to do so.
