### ISSUE TITLE
Increase the death timer to 4 or 5 minutes

### ISSUE THREAD

**Issue by GoodG1448** [BadDeathclaw/TG-Claw#350]
The current time from deffibing a dead body is of 2 minutes. Given the fact that deffibs aren't that common and cloning is non-existant in the wastes, there should be enough time to drag someone to a place in order to revive it. 

Taken from the /tg/wiki (Medical Doctor):

1. The patient must not be dead for more than **two minutes**.

2. The patient must not have over 180 brute or burn damage; 179 brute and 179 burn is fine, just not 180 of one type.

3. The patient must not be a suicide.

4. The patient must not be catatonic.

5. The patient must be in their body (they will get a message when they begin being defibrillated).

6. The patient must have a heart. 

https://tgstation13.org/wiki/Medical_doctor

**Comment by GhostEcho** [comment]
Good pr

**Comment by Monika4** [comment]
i'll have a look into to it and see if I can do it

**Comment by Monika4** [comment]
i think its because of DEFIB_TIME_LIMIT im unsure
