### ISSUE TITLE
Missing Vault Cargo Conveyor

### ISSUE THREAD

**Issue by Chronakai** [BadDeathclaw/TG-Claw#355]
There is no conveyor under the recycler in Vault Cargo, so the metal/glass/plasteel gets stuck underneath, requiring right/alt-clicking to pull them out. Working hazard! So that materials move from trash to recycler to the crate/unloading area, please add another conveyor linked to the other two underneath the machinery.

[Priority]: Minor Inconvenience
[PR]: Server revision compiled on: 2019-01-02
8d07483dac
Revision: 746734dfcbfe52ca678da9494997f7c4b9af37f8
[Reproduction]: Put lots of trash on the vault cargo conveyor belt, turn on belt, examine tile of recycler.
[For Admins]: N/A
[Notes]: N/A
![absolutely_unplayable](https://user-images.githubusercontent.com/5108584/50743891-acbf2580-11e2-11e9-881b-05db29a0acd8.png)

**Comment by JTGSZ** [comment]
Got it.
