### ISSUE TITLE
borgs are to op

### ISSUE THREAD

**Issue by EndaruI** [BadDeathclaw/TG-Claw#361]
Reporting client version: 512
**main issue**: replace disable beams with something that does not do stamina damage or remove them from the borgs
**smaller issues**:you cant even build a disabler as any faction I think only borgs have this  making this the best weapon ingame IMO (so why should borgs have acess to them hmm?)
**example**: I saw 3 bos getting cucked by a single sec borg. (a paladin a scribe and a initiate with all the rnd done had the advanced rifles) all he used was his disabler beam without the upgrade(if he had an upgraded version the battle would have ended so much sooner)

**retarded speach**: I know that ion rifles exist but who will carry a ion riffle for a random ass borg with his op disabler gun.
I also know you can ghost
****IF**** wastelanders had acess to those it would have been the most comon weapon used IMO
**question**: would you prefer to die instead of getting cuffed and dragged around god knows how long (ussualy pretty long and then they fucking kill you or make you serve time how long the owner of the borg wants)

**Comment by Monika4** [comment]
PR #353 my dude

**Comment by UndeadNappist** [comment]
Merged #353
