### ISSUE TITLE
Med-X shows doll health at 100% even after it runs out in the system

### ISSUE THREAD

**Issue by GhostEcho** [BadDeathclaw/TG-Claw#373]
While at first I wasn't too concerned with this, due to the fact that you could click yourself to examine damage to limbs, it's a different issue entirely when you have taken toxic damage. Not sure what causes it, but I think it should be fixed.

**Comment by imw-Oculus** [comment]
This is something I can fix. Working on it right now.

**Comment by imw-Oculus** [comment]
Fix complete. Compiling and testing now.

**Comment by imw-Oculus** [comment]
Fix works just fine. Closing issue.
