### ISSUE TITLE
Small cosmetic tweaks for helmets/masks.

### ISSUE THREAD

**Issue by GoodG1448** [BadDeathclaw/TG-Claw#374]
Let us see our hairs, beards and slutty lips by removing the tags highlighted in the pictures below. They should be easy to fix.

![dis](https://user-images.githubusercontent.com/38330373/51293654-a1dc7000-19ee-11e9-9866-36ee82f8d5d1.png)
![des2](https://user-images.githubusercontent.com/38330373/51293663-a6a12400-19ee-11e9-853e-e05b47106027.png)

For some reason, both metal mask block your hair despite not having HIDEHAIR tags. Sprite bug?

![what](https://user-images.githubusercontent.com/38330373/51293702-c5071f80-19ee-11e9-85f0-6fed2360f8ea.png)

**Comment by UndeadNappist** [comment]
If you know exactly what the issue is and what to edit it, why don't you do it?

I'm not mad or anything. Just extremely confused. If you need help or how to get started, feel free to ask one of the coders.

**Comment by GoodG1448** [comment]
I am running 32bit and Github Desktob doesn't work in 32 bit. Just pointing people in the right direction.

**Comment by UndeadNappist** [comment]
You can edit from the browser in your own repository.
![image](https://user-images.githubusercontent.com/7409796/52076476-9a1ae080-2543-11e9-9498-d2cf6ba4f313.png)

There is also gitkraken, amongst others.
https://www.gitkraken.com/
