### ISSUE TITLE
Scoped weapons can use their scope in belt and suit slots

### ISSUE THREAD

**Issue by GhostEcho** [BadDeathclaw/TG-Claw#383]
Super cheesy, allows people to snipe with weapons they shouldn't be able o snipe with due to a lack of scope

Also explain to me how the fuck this would work

Not I dead pls nerf, moreso I saw and was disgusted with it

**Comment by UndeadNappist** [comment]
if(!in_hand)
return

Something like that, anyway.

Move all zooming proc code out of the individual guns and weaponry and move it into /obj/item in zoom.dm, ensure the guns/binocs that zoom call on it and only that.

Step two is bugfixing the hell out of zooming. Recommend finding the least-broken zooming device and stamping all the others to use that code and tinkering from there (a harder chore).

**Comment by JTGSZ** [comment]
Solved by #577
