### ISSUE TITLE
Legion gets random weapons based on rank

### ISSUE THREAD

**Issue by JackofOak** [BadDeathclaw/TG-Claw#385]
Legion Random Weapons Suggestion(They starting bag equipment remains the same: Bola, Machete, Spears, etc.):

Rank 01: Recruit.

Possible Weapons:Recruit Possible Weapons - 38. Special, Single Shotgun, 
Remington, 9MM pistol

Rank 02: Veteran.

Veteran Possible Weapons - .44 Magnum, Winchester, Ithaca, 2 handed weapon (Fire Axe, Bu-
mper sword, Sledgehammer)), Rangemaster.

Rank 03: Vexillarius.

Vexillarius Possible Weapons- Scoped .44,Rangemaster, 9MM Submachinegun.

Rank 04: Decanus.

Decanus possible Weapons - (Same as Veterans) + 9MM Sub.

Rank 05: Veteran Decanus.

Vet.Decanus possible Weapons - Scoped.44, Thermic Lance, 10MM Submachinegun, 
Marksman Carbine.

Rank 06: Centurion

Centurion Possible Weapons - Bozar, Power Fist, Thermic Lance, Marksman Rifle.

This is all based on the fact that the legion is in no way a nation with uniformized
weapon standarts. Every firearm the a legionary have is one that he scavenged or
got from his fallen enemies. The possible weapons get stronger depending on the rank,
as legionaries have to prove themselves in order to advance in the ranks of the legion, thus
a higher ranking legionary must have killed well armed enemies, giving him better weapons
after such battles.

**Comment by GoodG1448** [comment]
> 
> Rank 01: Recruit.
> 
> Possible Weapons:Recruit Possible Weapons - **_38. Special_**, Single Shotgun,
> Remington, 9MM pistol
> 

Mind that the 38. special is actually the detective's revolver that briefly stuns people when a bullets hits them. It might come in handy for slave capturing, but letting the recruits have pseudo-tasers is kind of a weird change.

It has shit damage overall, might be balanced.
