### ISSUE TITLE
You can't properly deconstruct mineral doors

### ISSUE THREAD

**Issue by GoodG1448** [BadDeathclaw/TG-Claw#388]
This is a issue with wooden doors and metal ones. You used to be able to deconstruct metal and wooden doors with a screwdriver in Legacy (Both gave you 10 planks/sheets) . Now the only way to "deconstruct" is to smash it broken, which only deletes the door without leaving materials behind.

There should be atleast a way to deconstruct these doors while salvaging some materials from them, maybe add a lenghty progress bar for the whole thing.

**Comment by GhostEcho** [comment]
Yeah none of the tools work to deconstruct it, could use a deconstruction code

**Comment by GoodG1448** [comment]
Forgot to add image
![door](https://user-images.githubusercontent.com/38330373/51520129-a72c2700-1e01-11e9-8f38-78c9fcb2dbf2.png)

**Comment by UndeadNappist** [comment]
the mapped doors are machinery/doors/unpowered

mineral doors are /structure/

mapped doors need to be moved to /structure/doors (or similar) as well and have /machinery/doors/airlock be merged into machinery/airlock/ and machinery/doors/unpowered made defunct

**Comment by UndeadNappist** [comment]
Not quite done, machinery/doors/airlock needs to still be merged into machinery/airlock
