### ISSUE TITLE
CQC disabling the victim's vision even after they got back up

### ISSUE THREAD

**Issue by DanielMcFluffy** [BadDeathclaw/TG-Claw#389]
The fact that you can disable other people's vision for an unreasonable amount of time can ruin other player's experience. 

[Reproduction]: Harm intent-->Grab-->Click the victim--> CQC slammed-->hit the victim twice (while they're still downed) with hand

[Notes]: I haven't tried the other variants of CQC, might be worth to look into it.

**Comment by GhostEcho** [comment]
Can't recreate on most recent client version, assuming it's a client issue
