### ISSUE TITLE
Welding Helmet doesn't work. 

### ISSUE THREAD

**Issue by SpaceVampire** [BadDeathclaw/TG-Claw#393]
Issue reported from  Round ID: 746

Reporting client version: 512

I used it and my eyes still got stung.

**Comment by GhostEcho** [comment]
Tested welding helmet, seems to work fine, did you make sure you flipped the helmet down? Or were you by chance using the Arc Raider helmet? That one doesn't count as a welding helmet

**Comment by SpaceVampire** [comment]
I tested it again and couldn't reproduce the issue. I know the first time it happened the welding helmet was down, but the blind effect wasn't being applied for some reason.

**Comment by UndeadNappist** [comment]
If you can figure out the specific issue - or if it was the arc raider helmet - go ahead and create another issue for it.
