### ISSUE TITLE
Add clothing vendors to the map

### ISSUE THREAD

**Issue by MrDbaggy** [BadDeathclaw/TG-Claw#400]
I think it'd be a pretty cool idea to add some clothing vendors around the map so that people can have a larger choice of clothing for their characters instead of some select few which you may or may not during a round. I also think it could open up some roleplay, like how people will sometimes sell alcoholic beverages or food at the Den. They could possibly open up store selling clothing to wary wastelanders or raiders who get metagamed cause of their wacky clothing. I also think if you don't want everyone going around looking like freaks you can restrict certain clothings to raiders since for the most part they aren't all there.

**Comment by Cadwell-Regis** [comment]
It would be more lore friendly and less immersion breaking if someone doing the map added a clothes store or more clothing items to loot, as opposed to having a vending machine that does it. I believe a whole lot of armor, exosuit and clothing sprites are being ported in, so adding them in as loot is pretty easy - especially if there is a designated warehouse or structure for them to be bunched into.

**Comment by UndeadNappist** [comment]
Vending machines would be okay if they would actually eat money in exchange for their goods, but that should be a separate suggestion entirely.
