### ISSUE TITLE
Port the wild growing plants from Legacy code.

### ISSUE THREAD

**Issue by GoodG1448** [BadDeathclaw/TG-Claw#401]
We used to have xander/broc/mutfruit/ferrocactus back in the old code. I found the file looking around the old code:

![imagen](https://user-images.githubusercontent.com/38330373/51545266-5f78c000-1e40-11e9-954b-0671bbb644e6.png)

https://github.com/BadDeathclaw/bad-deathclaw/blob/master/code/game/objects/structures/wasteplants.dm

Found the sprites as well:
![imagen](https://user-images.githubusercontent.com/38330373/51553880-b4bdcd00-1e52-11e9-93d4-57baa3970450.png)

https://github.com/BadDeathclaw/bad-deathclaw/blob/master/icons/obj/Plants.dmi

EDIT: We seem to already have updated sprites in this repository. Looks taken from Outcasts.

![weas](https://user-images.githubusercontent.com/38330373/51660676-521d1c00-1f8d-11e9-835c-27a77ae7810d.png)

https://github.com/BadDeathclaw/TG-Claw/blob/master/icons/fallout/flora/flora.dmi

**Comment by UndeadNappist** [comment]
old codebase rng genned plants on the map
https://github.com/BadDeathclaw/bad-deathclaw/blob/64ba57582479059dd91819603d9ccba356842ca8/code/game/objects/structures/flora.dm
