### ISSUE TITLE
Add logging for pulling a gun out into your hand or picking one up

### ISSUE THREAD

**Issue by UndeadNappist** [BadDeathclaw/TG-Claw#447]
If someone else doesn't get to this I will. Check out my PR for sending logs to admins when the vault is open for a place to start.

Would also be good for a to_chat message whenever you whip out a pistol so people who are distracted with RPing can drop what they're doing and shoot you.

Third, maybe a delay between drawing and firing a weapon, based on the size of the weapon and where you're drawing it from (clearing it from a holster will have a shorter delay, for example).

**Comment by Cadwell-Regis** [comment]
I asked about this a long time ago and told it didn't matter, that rules prevent problems like this from happening. It would probably do wonders, in all honesty and help deal with situations where people get killed during roleplay.

**Comment by Cadwell-Regis** [comment]
I've heard the argument people will run around with guns out in the open all the time.

That makes them a threat to everyone, which is much - much better then people being able to quickdraw kill people in an instant. We've talked this over before and it's very clear, it's much better for people to be CLEARLY armed and dangerous. Then for  them to appear harmless to then draw a gun in 0.5 milliseconds and murder someone.

**Comment by Kimochiiiiiiiiiiiiii** [comment]
I'm not defending the quickdraws and shooting someone dead 1 second after a word is said. But people carried and still carry weapons and blunts on their hands without a reason to do, or for example to fend off mutants. Allowing anyone with a gun in their hands to be shot if they are met by another player is shit, and many will say in ahelps when the victim complains "I thought he was going to shoot me; he walked towards me with a gun; he shot his gun near me". Secondly, this is not the thing that will help people from shooting each othet, but the other way around. I don't know what you're trying to mean about quickdrawing being meta, but I don't think the term applies here. Also, escalation rules only force the playerbase to initiate an arena-like fight and pretty much just that, and discredits any other method of fighting that requires the other party to not know their fate, from whatever party it be, such as deadly pills, sniping and assasinations out of the blue, the ways of dying that would seem the mostly common in the post-apocalyptic America. It's not like the delay and chat warning will help at all times neither, in big crowded areas people will be confused trying to hold one or three conversations while reacting to the active shooter at the same time, or even worse, having the guy be named Unknown. This delay will create problems.

**Comment by UndeadNappist** [comment]
#612
