### ISSUE TITLE
R&D is terrible, it needs to be fixed, suggest ideas

### ISSUE THREAD

**Issue by UndeadNappist** [BadDeathclaw/TG-Claw#464]
Currently, R&D is a simple mechanic of watching a point counter go up as time passes, pressing buttons, then inserting goods to receive powergaming stuff.

It lacks the interesting, further depth of even chemistry where you create your own mixtures or do various shenanigans or give and take to create an organic and intricate system and actually creates a problem where it crushes people's creativity to explore other aspects of the game.

Suggest some alternative ways to change it from button-pressing to a deeper system with a simple introduction that can then develop into game-changing complexity.

I am not asking for coding at this time - good ideas are fine.

**Comment by GhostEcho** [comment]
we could port this and make rnd similar http://ss13.moe/wiki/index.php/Mechanic

**Comment by LetterN** [comment]
you can hide nodes behind real objects
