### ISSUE TITLE
Mounds for buried things

### ISSUE THREAD

**Issue by UndeadNappist** [BadDeathclaw/TG-Claw#465]
Need a bulge of dirt that overlays ontop of the sand when someone buries an object, varying in size from small, medium, to large.

Or alternatively Disturbed Earth, Buried Object, Dead Body sizes.

**Comment by GoodG1448** [comment]
Here, I just recolored the dirt mould used for planting stuff on it.
![bump](https://user-images.githubusercontent.com/38330373/52078656-7c18a480-2572-11e9-877f-ab2b4a435f3a.png)

**Comment by kilozombie** [comment]
Small mound should be very very hard to see so you can still bury stuff in the desert and have a good chance it won't be found

**Comment by GoodG1448** [comment]
Ok, just finished the medium and small mound. The picture shows how they should look like on a normal desert tile.
![preview](https://user-images.githubusercontent.com/38330373/52092803-9022cd00-2597-11e9-8212-95ba0cac30e1.png)
![megaweed](https://user-images.githubusercontent.com/38330373/52092807-931dbd80-2597-11e9-9379-b425b55129a8.png)

**Comment by kilozombie** [comment]
Awesome, I really like the look of these. Well done!
