### ISSUE TITLE
Continue implementing/porting new borg icons/adding new borgs

### ISSUE THREAD

**Issue by UndeadNappist** [BadDeathclaw/TG-Claw#469]
Porting eyebots and other skins from the old codebase ( https://github.com/BadDeathclaw/bad-deathclaw )
Adding new kinds of cyborg (firefighter, construction worker, emergency responder - which means splitting up modules and narrowing focus of each 'borg)
etc.

**Comment by Kimochiiiiiiiiiiiiii** [comment]
I think that each of them having a special weapon would be good too, an emergency responder having traitor paddles, a firefighter havong a flamethrower, and so on.

**Comment by GoodG1448** [comment]
Added the old eyebots sprites and deleted the that spider-like drone sprites.
![drones](https://user-images.githubusercontent.com/38330373/52117159-cbea8080-25f1-11e9-8c6f-b668040e57d4.png)
https://cdn.discordapp.com/attachments/470357948024225822/540838918854017026/drone.dmi
