### ISSUE TITLE
Rebalance all guns

### ISSUE THREAD

**Issue by UndeadNappist** [BadDeathclaw/TG-Claw#471]
A lot of people have uploaded some really nice sprites for various guns (including the HK CAWS) amongst others. What needs to be done is;
-Make longarms not fit on the belt, only the back.
-Make longarms not fit in suit storage.
-Rebalance the guns themselves so they can be re-added to the game and we can actually see them again.

**Comment by Cadwell-Regis** [comment]
I worked with Oculus for weeks rebalancing all the ammo, so we should be fine post-update for damage / AP balancing for ammo. There's more benefit to single shot high damage guns over rapid fire weapons when dealing with armor.

**Comment by RenGusta** [comment]
If it's not the set I went through and balanced, I wouldn't like to see it. 

I spent plenty enough of my time correcting an entire document
