### ISSUE TITLE
Add lootspawns for ghouls

### ISSUE THREAD

**Issue by UndeadNappist** [BadDeathclaw/TG-Claw#481]
Ghouls should drop bloody or dirty clothing on death. Don't give them anything useful like guns or ammunition - but shoes, costumes, bags, etc, etc. Try to build them in "sets" so you get the feeling you just murdered a random civilian ex-person.

**Comment by GoodG1448** [comment]
I have no idea on how to code, but I think borrowing some things from the Legion mob could make this work.

![geasda](https://user-images.githubusercontent.com/38330373/52144317-adf63d80-263c-11e9-811c-45c89b2c3742.png)
https://github.com/BadDeathclaw/TG-Claw/blob/master/code/modules/mob/living/simple_animal/hostile/mining_mobs/hivelord.dm#L91

**Comment by UndeadNappist** [comment]
@GoodG1448 You're already ahead of some newbie coders. Have more confidence in yourself.
