### ISSUE TITLE
Advanced Weapons don't have authorization pins by default

### ISSUE THREAD

**Issue by SpaceVampire** [BadDeathclaw/TG-Claw#490]
Issue reported from  Round ID: 849

Reporting client version: 512

When you print a Advanced Weapon from a protolathe it has an electronic firing pin installed.
It used to be a weapon authorization firing pin.

**Comment by GhostEcho** [comment]
Id have to label this not a bug

**Comment by RenGusta** [comment]
I don't know why you'd complain about it being easier to use an RND weapon, given we nerfed the ease with which you can get weapon auth implants.
