### ISSUE TITLE
Ghost role sleepers.

### ISSUE THREAD

**Issue by JessieProudmore** [BadDeathclaw/TG-Claw#494]
Sleepers. The sleepers that use ghosts to create a new character. The ones already in default ss13.
This would be helpful for events since an admin wouldn't need to offer bodies to ghosts constantly. Instead, just spawn in the sleeper (That spawns a random human with no gear or clothes) so an admin can place gear beside the sleeper for the now event character to use. This would be better since it will be available to ghosts at all times and be lost once it's taken.

**Comment by Kimochiiiiiiiiiiiiii** [comment]
Ghosts will take those slots even when there's no event and maybe suicide later, making the whole thing crumble down for you to need to spawn humans manually. Is it that hard?

**Comment by JessieProudmore** [comment]
Thing is, it shouldn't be able to create ghost spawners until the admin creates it. Making it easier and less of a process to repeatedly offer a role to ghosts.
