### ISSUE TITLE
Mining monsters

### ISSUE THREAD

**Issue by UndeadNappist** [BadDeathclaw/TG-Claw#501]
Add monsters that become increasingly likely to spawn the better your mining tool is. The default pickaxe would not cause monsters to spawn.

You could make the monsters super-dangerous, thereby allowing people with plasma cutters to make the decision to mine safe or mine dangerous.

Worms, rock monsters, etc.

**Comment by UndeadNappist** [comment]
![image](https://user-images.githubusercontent.com/7409796/52173653-4a076e00-273d-11e9-861f-2a7d1c69fb45.png)

**Comment by GoodG1448** [comment]
We had molerats in Legacy. I guess that would work, wouldn't be that dangerous for the BoS though.

**Comment by UndeadNappist** [comment]
> We had molerats in Legacy. I guess that would work, wouldn't be that dangerous for the BoS though.

We can arbitrarily buff the hell out of them by giving them -20 speed and 100 damage melee attacks. It doesn't really matter. Just need sprites and code done.

**Comment by GoodG1448** [comment]
The sprites are there. The only issue is that I didn't found any files with the code for the molerats, atleast nowhere near the simple_mobs folder in the Legacy repo.
![mobs](https://user-images.githubusercontent.com/38330373/52182701-72937480-27de-11e9-923b-d4383572d90f.png)

It shouldn't be too hard to copy paste the radroach and slap the molerat sprite though.

**Comment by MrDbaggy** [comment]
Sounds good anything that makes mining more interesting is A okay with me
