### ISSUE TITLE
Runtime Tracker - Do Not Close

### ISSUE THREAD

**Issue by GhostEcho** [BadDeathclaw/TG-Claw#502]
Post runtimes here admins and coders with access to the runtime logs 
ckey and playername are where those two would usually show up in the logs, edited out for privacy

**Comment by GhostEcho** [comment]
[05:47:51] Runtime in unsorted.dm, line 1225: addtimer called with a callback assigned to a qdeleted object. In the future such timers will not be supported and may refuse to run or run with a 0 wait

**Comment by GhostEcho** [comment]
[06:11:51] Runtime in rdconsole.dm, line 1051: Cannot execute null.Cut().

**Comment by GhostEcho** [comment]
Runtime in _techweb.dm, line 292: Cannot execute null.rescan views()
 Runtime in _techweb.dm, line 86: Cannot execute null.rescan views().

**Comment by GhostEcho** [comment]
Runtime in adminhelp.dm, line 474: Cannot execute null.verbs().

**Comment by GhostEcho** [comment]
Runtime in chem_dispenser.dm, line 82: Cannot execute null.give().

**Comment by GhostEcho** [comment]
Runtime in good.dm, line 24: Cannot execute null.GetComponent()

**Comment by GhostEcho** [comment]
Runtime in chem_dispenser.dm, line 153: Cannot execute null.charge

**Comment by GhostEcho** [comment]
Runtime in airlock.dm, line 356: Cannot execute null.is cut()

**Comment by GhostEcho** [comment]
[08:31:43] Runtime in mech_fabricator.dm, line 152: Undefined variable /obj/mecha/working/ripley/var/materials 

proc name: build part (/obj/machinery/mecha_part_fabricator/proc/build_part)
usr: Paxton Williamson (serwigglesworth) (/mob/living/carbon/human)
usr.loc: The vault floor (87,277,2) (/turf/open/floor/plasteel/f13/vault_floor/blue)
src: the exosuit fabricator (/obj/machinery/mecha_part_fabricator)
src.loc: the vault floor (111,261,2) (/turf/open/floor/plasteel/f13/vault_floor/purple/whitepurplefull)
call stack:
the exosuit fabricator (/obj/machinery/mecha_part_fabricator): build part(APLU (\"Ripley\") Completed (/datum/design/ripley_Whole))
the exosuit fabricator (/obj/machinery/mecha_part_fabricator): process queue()

**Comment by GhostEcho** [comment]
[08:34:51] Runtime in tgui.dm, line 87: Cannot read null.client
proc name: open (/datum/tgui/proc/open)
src: /datum/tgui (/datum/tgui)
call stack:
/datum/tgui (/datum/tgui): open()
the sleeper (/obj/machinery/sleeper): ui interact(null, "main", /datum/tgui (/datum/tgui), 0, null, /datum/ui_state/notcontained_s... (/datum/ui_state/notcontained_state))
the sleeper (/obj/machinery/sleeper): updateUsrDialog()
the sleeper (/obj/machinery/sleeper): open machine(1)
the sleeper (/obj/machinery/sleeper): open machine()
the sleeper (/obj/machinery/sleeper): container resist(Angela Hawker (/mob/living/carbon/human))
the sleeper (/obj/machinery/sleeper): relaymove(Angela Hawker (/mob/living/carbon/human), 1)
Mynameajeff (/client): Move(the vault floor (97,252,2) (/turf/open/floor/plasteel/f13/vault_floor/misc/rarewhite), 1)
Angela Hawker (/mob/living/carbon/human): keyLoop(Mynameajeff (/client))
Mynameajeff (/client): keyLoop()
Input (/datum/controller/subsystem/input): fire(0)
Input (/datum/controller/subsystem/input): ignite(0)
Master (/datum/controller/master): RunQueue()
Master (/datum/controller/master): Loop()
Master (/datum/controller/master): StartProcessing(0)

**Comment by GhostEcho** [comment]
[08:47:46] Runtime in radiation.dm, line 19: Cannot read null.type
proc name: get rad contents (/proc/get_rad_contents)

**Comment by GhostEcho** [comment]
[09:12:11] Runtime in parallax.dm, line 149: Cannot modify null.parallax_animate_timer.
 proc name: update parallax motionblur (/datum/hud/proc/update_parallax_motionblur)

**Comment by GhostEcho** [comment]
[09:16:11] Runtime in emote.dm, line 63: Cannot execute null.get reagent().
proc name: can run emote (/datum/emote/living/cough/can_run_emote)
usr: player (ckey) (/mob/dead/observer)
usr.loc: The floor (86,258,2) (/turf/open/floor/plasteel/f13)

**Comment by GhostEcho** [comment]
[03:01:43] Runtime in asset_cache.dm, line 98: Cannot read null.cache
proc name: send asset list (/proc/send_asset_list)
usr: ckey () (/mob/dead/new_player)
src: null
call stack:
send asset list(null, /list (/list), 0)
/datum/browser (/datum/browser): open(0)
ckey (/mob/dead/new_player): new player panel()
ckey (/mob/dead/new_player): Login()
New(null)

**Comment by RedTekRedd** [comment]
runtime error: bad index
proc name: Get (/datum/controller/configuration/proc/Get)
  source file: configuration.dm,159
  usr: null
  src: Configuration (/datum/controller/configuration)
  call stack:
Configuration (/datum/controller/configuration): Get(/datum/config_entry/number/err... (/datum/config_entry/number/error_msg_delay))
 (/datum/error_viewer/error_cache): log error(list index out of bounds (/exception), /list (/list), null)
world: Error(list index out of bounds (/exception), null)
/datum/getrev (/datum/getrev): New()
world: New()
[18:05:01] Runtime in getrev.dm,18: list index out of bounds
  proc name: New (/datum/getrev/New)
  src: /datum/getrev (/datum/getrev)
  call stack:
  /datum/getrev (/datum/getrev): New()
  world: New()

**Comment by GhostEcho** [comment]
[00:19:34] Runtime in human_defense.dm, line 30: Cannot read null.body_part
proc name: checkarmor (/mob/living/carbon/human/proc/checkarmor)
usr: playername (ckey) (/mob/living/carbon/human)
usr.loc: road (175,116,2) (/turf/open/floor/plating/f13/outside/road)

**Comment by GhostEcho** [comment]
00:57:30] Runtime in parallax.dm, line 169: Cannot read null.eye
proc name: update parallax (/datum/hud/proc/update_parallax)
usr: playername (ckey) (/mob/dead/observer)
usr.loc: The vault floor (161,12,1) (/turf/open/floor/plasteel/f13/vault_floor/purple/whitepurplefull)

**Comment by GhostEcho** [comment]
[01:11:48] Runtime in customizables.dm, line 122: list index out of bounds
 proc name: update overlays (/obj/item/reagent_containers/food/snacks/customizable/update_overlays)

**Comment by GhostEcho** [comment]
<<<Refresh

[08:42:01] Runtime in , line : bad arg name 'Type'
proc name: presentpicker (/proc/presentpicker)
usr: Ara (ghostechoe) (/mob/dead/observer)
usr.loc: desert (127,216,2) (/turf/open/floor/plating/f13/outside/desert)
src: null
call stack:
presentpicker(Ara (/mob/dead/observer), "Modify armor", "Modify armor: the executive su...", "Save", "Cancel", null, null, 0, null, null, null, null, null)
GhostEchoe (/client): view var Topic("_src_=vars;admin_token=0657616...", /list (/list), null)
GhostEchoe (/client): Topic("_src_=vars;admin_token=0657616...", /list (/list), null)
GhostEchoe (/client): Topic("_src_=vars;admin_token=0657616...", /list (/list)) 

dgaf about my own info being here

**Comment by GhostEcho** [comment]
[09:20:34] Runtime in hologram.dm, line 422: Cannot execute null.say().
proc name: Hear (/obj/machinery/holopad/Hear)
usr: playername (ckey) (/mob/living/carbon/human)
usr.loc: The vault floor (181,33,1) (/turf/open/floor/plasteel/f13/vault_floor)

**Comment by GhostEcho** [comment]
[08:49:17] Runtime in death.dm, line 37: Cannot read null.species
proc name: death (/mob/living/carbon/human/death)
usr: Unknown () (/mob/living/carbon/human)
src: Unknown (/mob/living/carbon/human)
src.loc: null
call stack:
Unknown (/mob/living/carbon/human): death(null)
Unknown (/mob/living/carbon/human): update stat()
Unknown (/mob/living/carbon/human): updatehealth()
Unknown (/mob/living/carbon/human): take overall damage(0, 0, 0, 1)
Unknown (/mob/living/carbon/human): adjustBruteLoss(200, 1, 0)
Unknown (/mob/living/carbon/human): suicide()

**Comment by GhostEcho** [comment]
[20:57:50] Runtime in browserOutput.dm, line 109: bad client
proc name: showChat (/datum/chatOutput/proc/showChat)
src: /datum/chatOutput (/datum/chatOutput)
call stack:
/datum/chatOutput (/datum/chatOutput): showChat()
/datum/chatOutput (/datum/chatOutput): doneLoading()
/datum/chatOutput (/datum/chatOutput): start()

**Comment by GhostEcho** [comment]
Semi high Priority one here, spit out a shitton when it was triggered

[03:20:08] Runtime in proximity.dm, line 112: Cannot read null.hasprox_reciever
[03:30:45] Skipped 98 runtimes in proximity.dm,112.

**Comment by Hekzder** [comment]
This should theoretically stay open, but hasn't been commented on since Feb. 10th. We normally just post runtimes and deal with them in house amongst the coding staff, we don't really need a Github issue for this.
