### ISSUE TITLE
Random EXPERIMENT button on the Overseer's computer

### ISSUE THREAD

**Issue by UndeadNappist** [BadDeathclaw/TG-Claw#505]
Press a button, receive a VAULT-TEK verified experiment. Sky's the limit. Examples of what to show available:
Milgram Experiment,
A Class Divided,
Asch Conformity Study,
Bobo Doll Experiment,
etc. A short description of how to set up the psychological experiment and what to do, but not what the end result is or the actual IRL name.

**Comment by Cadwell-Regis** [comment]
If we ever get enough staff, I'd love to see a lot of these 'features' be done by the admins. I always felt like they're ultimate calling should be gamemastering and telling stories, seems like they are wasted just dealing with rule breaking and glitches. 

Just need more people...

**Comment by LetterN** [comment]
can add as an in-game feature, like those goals on tg like build a bsa etc....

**Comment by UndeadNappist** [comment]
Yeah, I'd basically just make it replace the centcom report and work the same way, except you can gen/print out another random one if you want to see a new one.
