### ISSUE TITLE
Job Summary Message

### ISSUE THREAD

**Issue by UndeadNappist** [BadDeathclaw/TG-Claw#515]
Summary of the job and what you are expected to do in a pop-up window when you enter the game, like happens for literally every other server.

**Comment by RenGusta** [comment]
Huge list exists. Caden/Regis has it all together. I believe @JarlElbow was going to do it at one point. If anyone wants to take it, talk to Regis.

**Comment by JarlElbow** [comment]
I'm 90% sure it got added for most faction jobs, aside from raiders and the Den. 
So if you aren't seeing them, I'm not sure what's up.

**Comment by UndeadNappist** [comment]
It does, I wasn't paying close enough attention - I assumed you'd add it as a bigass popmenu that would appear over the screen as I'm used to.
