### ISSUE TITLE
Mop Typo

### ISSUE THREAD

**Issue by RedTekRedd** [BadDeathclaw/TG-Claw#517]
“You mop dry” message.

**Comment by RedTekRedd** [comment]
Am told this is meme. Close this if that’s the case.

**Comment by Kimochiiiiiiiiiiiiii** [comment]
It's a meme from drymouth gulch, godsring official gaym. You can't close something so old, even if you dislike memes, feggit.

**Comment by UndeadNappist** [comment]
Don't be rude @Kimochiiiiiiiiiiiiii 
It's just a joke, why you gotta be mad.
