### ISSUE TITLE
ERP Verbs

### ISSUE THREAD

**Issue by tacticalpractical** [BadDeathclaw/TG-Claw#523]
Spawn as a female character, and you can open up the erp verbs and breast grope anybody. If you span as a male character, you don't have that option in your erp verbs.

**Comment by Cadwell-Regis** [comment]
This will probably be fixed at some point, but making ERP better is really down the list in terms of stuff being done.

The staff don't think of ERP as integral to the server, it is something we'd like to work on for you know - the people who want to bump fuzzies, no shame to them, we've all got our thing.

But there are a lot of features, fixes and balances still getting worked on which take priority, which I  think you'd probably agree are more important. But one day, ERP will be fixed and it will probably be sort of cool.

**Comment by codexcode** [comment]
I have nothing better to do so I’ll take a look when I get home later.

**Comment by codexcode** [comment]
@tacticalpractical submit screenshots to me on discord @Redd The Dragon#0419

I can’t even find grope code.

**Comment by DIamonnd** [comment]
Its most likely a problem on who is allowed to do the verb. Seems that is instead of checking if the target has breasts to allow the groping or not, it checks on your player. Making only women be capable of groping people instead of women being the only ones able to be groped.
