### ISSUE TITLE
Bank machines do not accept reskinned space cash (NCR money)

### ISSUE THREAD

**Issue by ErwinSnowden** [BadDeathclaw/TG-Claw#526]
[Priority]: Low

[PR]: The space cash acceptance wasn't changed to NCR cash(?)

[Reproduction]: Admins spawned in a bank machine, gave us additional funds to order crates as vault, couldn't put in NCR money which comes out of the service fabricator in borgs.

[For Admins]: This was by admin intervention but it seems like an issue in consistency with the code of space cash and not var-editting.

[Notes]: N/A

**Comment by JTGSZ** [comment]
Solved by #581
