### ISSUE TITLE
Stop resetting my job preferences on every new round

### ISSUE THREAD

**Issue by kilozombie** [BadDeathclaw/TG-Claw#532]
This can't be that hard, can it?

Other codebases even let me have custom job preferences for each of my characters, but in this I have to manually set it after every round end, and have to remember exactly what I chose for each individual characters. If I forget, stupid stuff happens like having a Raider spawn as NCR or other unexpected, unwanted results.

**Comment by kilozombie** [comment]
Note: this isn't a huge problem if you don't ready up and just join immediately after the round starts, but for command roles or BoS or other limited slot roles, forgetting this could be very frustrating and having to do it each time is equally frustrating, to me.

**Comment by Kimochiiiiiiiiiiiiii** [comment]
yep

**Comment by JTGSZ** [comment]
Solved by #546
