### ISSUE TITLE
More dynamic Chemistry/OD system

### ISSUE THREAD

**Issue by UndeadNappist** [BadDeathclaw/TG-Claw#537]
Change the recipes around so to make poisons you have to blend medical and random chemicals together ; reduce the overall severity of ODs (or buff poisons) to compensate for this added complexity; make certain kinds of healing blends impossible or severely dangerous by having chemicals react into discreet things.

I am by no means advising adding more of different kinds of chemicals. Effects should be more or less unique, or have specific drawbacks or gains to emphasize the difference.

You CAN, however, add multiple ways to create the same chemical.

There should still be some leeway added - to reward people who specialize and understand the chemicals - but it shouldn't be as easy as "Grab recipe list"

An alternative method to overdosing could be making recipes that are 30u of chemical and 1u of blood.

Edit: You can also define ANYTHING under the overdosing(), so you could add hallucinations, adding skewium, or other really !FUN! stuff to mess with people. Sky's the limit, draw on RL inspirations.

**Comment by Raze500** [comment]
About the poisons...Like adding chemicals that you need to grind? like plasma... uranium and stuff?

Also just poisons **right?** not medicine? I would gladly work in this of course.

> Don't nerf everything that i like pls nappist

**Comment by UndeadNappist** [comment]
Nah, more like derivatives of medicines like you expect real-world meds to be, or just make it more complicated to make bundles of healing chems because the chemicals have Bad Interactions in your body and poison you - again, just like RL ones.

**Comment by Raze500** [comment]
Like it heals but gives you little tox or oxy dmg/sleepyness?

**Comment by Raze500** [comment]
Like i have a sickness one and makes me kinda sleep, ah sounds reasonable
