### ISSUE TITLE
Fisto apparently doesn’t work

### ISSUE THREAD

**Issue by RedTekRedd** [BadDeathclaw/TG-Claw#548]
RenGusta informed me they don’t work. Will investigate.

**Comment by RedTekRedd** [comment]
Looking over the code, I believe the addition of colors to a certain lewd object may have broken fisto

**Comment by RedTekRedd** [comment]
Never mind. Testing has confirmed the issue. Admin spawned borgs with the module pre-selected (/mob/living/silicon/robot/sexyhandy or /mob/living/silicon/robot/fisto_protectron) work. Newly created cyborgs who select the module do not. Further investigation needed.

**Comment by LetterN** [comment]
#822
