### ISSUE TITLE
Increase overall crafting time ; allow multi-crafting to take exactly the same amount of time

### ISSUE THREAD

**Issue by UndeadNappist** [BadDeathclaw/TG-Claw#553]
Increase crafting time for many recipes, but make it take the exact same amount of time to craft multiples of the recipe.

Adding a x5 next to foods or healing powder, for example.

**Comment by Raze500** [comment]
Sounds interesting :^) i will try.

**Comment by Raze500** [comment]
I dunno how it will work... all the recipes spawn only 1 item hah!

**Comment by rhicora** [comment]
Some recipes could have the `can_craft_five` or `can_craft_ten` flags, in which case a conditional x5 or x10 button would be rendered next to the normal Craft one. It will multiply the resources used and yield but take the same amount of time.

This will prevent handcrafting things like healing powder in combat, but allow Camp Followers / NCR Citizens / Den docs etc to create batches of things faster.

**Comment by Raze500** [comment]
Thanks mother coder for the tip!
