### ISSUE TITLE
Add knocking

### ISSUE THREAD

**Issue by UndeadNappist** [BadDeathclaw/TG-Claw#554]
Add a knock.ogg that plays, on a cooldown timer, with all the important checks to make sure people don't spam it and lag the server and sound falloff so you can knock on doors.

Probably set to disarm or something when you click on an obj/structure/mineral_door or /obj/machinery/door/airlock/door (don't ask why the second one exists please)

**Comment by Kimochiiiiiiiiiiiiii** [comment]
+1

This is obviously needed, both for rp and mechanics' improvement.
