### ISSUE TITLE
Rework telecomms/radio

### ISSUE THREAD

**Issue by UndeadNappist** [BadDeathclaw/TG-Claw#555]
This is going to be a horrible issue that's going to require a lot of effort, so if you're digging into this good luck and I recommend tackling it as a group project.

Persistence has already gotten started on something like this if I'm not mistaken.

Rework telecomms to be factionalized instead of global.
Remove headsets from autolathes and the like, and leave bounced radios instead.
Limit the range of bounced radios to a maximum number of squares around them.

**Comment by Raze500** [comment]
Holy fuck indeend nappist.
