### ISSUE TITLE
Borgs can't use R&D Consoles

### ISSUE THREAD

**Issue by Tename** [BadDeathclaw/TG-Claw#556]
Issue reported from  Round ID: 933

Reporting client version: 512

When any borg attempts to use the R&D console it displays this message "The array of simplistic button pressing confuses you. Besides, did you really want to spend all day staring at a screen?". This makes it so engineering borgs can't print parts for their RPED.

**Comment by UndeadNappist** [comment]
They don't have TRAIT_TECHNOPHREAK. Personally, I find this hilarious, but I should probably change it.

**Comment by UndeadNappist** [comment]
#620
