### ISSUE TITLE
Give NCR a box of dogtags they can rename

### ISSUE THREAD

**Issue by companoo** [BadDeathclaw/TG-Claw#574]
make it so like

you can set your role as a medic or an engineer or a whatever
but it still has trooper there
maybe even do the campfollower thing and find some way to select your gear idk

**Comment by Kimochiiiiiiiiiiiiii** [comment]
The actual way of doing things seems okay for the most part, there's already troopers that go, get medical supplies and make themselves the pharmacist of the outpost, and even the construction worker. 
Though, what do you mean by "Campfollower"? Are you referring to a role that works on the NCR's farms?

**Comment by companoo** [comment]
camp followers have a chance to spawn with different gear

**Comment by companoo** [comment]
i think its like jobs so like miner gets a pickaxe and shit

**Comment by Kimochiiiiiiiiiiiiii** [comment]
I don't think it's a good addition, it just seems pointless and would only conplicate things more

**Comment by thedumbfish123** [comment]
add these badges into the game, i think they will be a great addition
