### ISSUE TITLE
Ragged clothes modifier

### ISSUE THREAD

**Issue by Kimochiiiiiiiiiiiiii** [BadDeathclaw/TG-Claw#582]
Adding a modifier to every instance of clothing/armour that would make it deteriorate at a specific rate every five/ten minutes depending on what the item is (for example, power armour would break up on a slower rate, but settler uniforms and tan coats at a faster one. The modifier being affected by time, combat and environment. ) would make as incentive for people to care more about their surroundings and thus the immersion from my point of view.

**Comment by UndeadNappist** [comment]
That would be really annoying and #156 and the various issues around gun balance.

Yes, it would help balance the game.

But it wouldn't be fun. We're not an MMORPG, so all the junk disappears in a few hours anyway. Your treasure horde is only temporary.
