### ISSUE TITLE
Remove powergamer fluff

### ISSUE THREAD

**Issue by ErwinSnowden** [BadDeathclaw/TG-Claw#583]
Implants, chems, tools, power armor, antagonists, and every other gimmicky powergame bullshit from /tg/ should be removed. It only causes unrest, and imbalance in the rounds. Energy weapons need to be removed, all they are used for is a permanent alternative to bullets as they take nothing to refill due to how power code is handled, combat as a whole needs to be reworked, technology severely nerfed because of radiation, everybody in the vault should be a roundstart pacifist as they wouldn't hurt anybody due to American values. Antagonists should be removed because we'll never really use them, I should be able to ERP anyone, regardless of clothing. Thank you for listening to my complaints.

**Comment by RenGusta** [comment]
This PR is a joke. And if it isn't, you have a poor perception of balance.

If you continue to make comments and Issues that are entirely stupid, you will be banned from commenting on the Repo. 

You will not be warned again.
