### ISSUE TITLE
Replace quirks with fallout perks

### ISSUE THREAD

**Issue by Kimochiiiiiiiiiiiiii** [BadDeathclaw/TG-Claw#592]
Quirks are **rarely** used to improve immersion and to create a character with a certain advantage or disadvantage, instead, you get players that use the system to get the least harmful negative quirks for the sweet positive bonuses. Getting things like nyctophobia and family heirloom only to gain skills like Life Giver or Big Leagues should be considered powergame.

This is from a random player I saw when ghosting: 
![afadec2bf516a253a09cdc495129f8e1](https://user-images.githubusercontent.com/47223562/52919553-def49480-3303-11e9-9674-165ad3510e73.png)

Just so I stand clear, remove all quirks or (admins) moderate their use.

**Comment by Raze500** [comment]
Making the family heirloom free, deviant tastes to +1 and Really dissociation syndrome to free i guess too... and depression? hah...

**Comment by GhostEcho** [comment]
Family Heirloom should definitely free, as well as deviant tastes being +1, RDS should be kept as is as it will fuck you over occasionally, prosthetic limb should either be free OR +1, not a -1, it's easily a sidegrade as you don't have to waste medicine on the limb, just an easily printed welder or cables. Nyctophobia is tricky for me, as it means if you want to move fast at night, you can only do so with a HERE'S ME light around you

**Comment by GhostEcho** [comment]
Depression shouldn't be free, but it should lock you out of apathetic and jolly

**Comment by UndeadNappist** [comment]
Planned system for replacing quirks with self-balancing perks. Ask Ren for the instructions, although someone else will have to code.

**Comment by Kimochiiiiiiiiiiiiii** [comment]
Yo nigga nappist that wasn't the title, why you changing muh shit

**Comment by RenGusta** [comment]
As per what Nappist said. I'm writing up design documents over the next few days and perk overhaul is first on the list. The current set will be 'extra' perks, selectable in any amount, as they're mostly flavour. The actual list and benefits of selections will be much larger and in depth than "you take negative get positive, xd"

**Comment by UndeadNappist** [comment]
https://goo.gl/forms/rwwUQeuyA3YYzVZv2 smoke 'em if you got 'em
