### ISSUE TITLE
Add weather for Immersion / Challenge / RP!

### ISSUE THREAD

**Issue by Murderfoxen** [BadDeathclaw/TG-Claw#603]
### The Concept:

Concept is that various weathers can spawn, potentially detectable via warnings, with little to no exact time in knowing exactly when. This creates an immersive atmosphere that can add to HRP as people develop a need to shelter themselves through elements they cannot always foresee.  This could even go as far as to prevent initial Meta-Rush, if you think about it. 

### New Items/commands to incorporate the system:

**Potential new items:** 
- Weather-Forecast device: When used, reads the next incoming weather-pattern. It could be more accurate than the command suggested below, giving people to favor it over simply using their eyes. Perhaps the device gives a specific time reading of when weather hits?
 (Really not sure on a name, frankly.)

**Potential new command:**
- Check Weather: A simple command to tell/notify players of incoming weather. Could be vague intentionally, such as: "I can see clouds forming. They seem dark." or it could be as obvious as: "You sense a Rad-storm coming soon.. " - whichever works.

If the system is hard to discern for players, this would intentionally simulate real meteorology and it's fickle nature, allowing for some difficulty and risk elements for those who might want to embrace it. 

### Weather-Types:
**Rain**: Simple enough, suggested a few times. (Potentially an easy reskin of dust storms) - Would clear away blood and footprints. Could water plants automatically, as well as fill up buckets/containers with water. Water /could/ be radioactive. 

**Thunderstorm:** Similiar to Rain, with potentiality for thunderstrikes. Could be used to gather rudimentary electricity, or punish those who wear too much metal and venture out amidst one - giving them burn damage when struck. Alternatively, could just be an aesthetic difference with moody undertones. 

**Dust-storms:** A Mojave Wastes special. The dust storms obscure vision and impede progress. Most likely adding an extra element to would-be raiders who like to travel in the protection of blindness. This would end up being quite lethal, as the mobs spawning in low-visibility and auto-pathing would have a strong advantage over less robust players who do not read chat to see when they have Aggro'd a mob. 

**Rad-Storms:** Probably the most lethal Idea, frankly. A rad-storm would be a green-hued thunderstorm with a radioactive effect if exposed directly to the rain. It would be something almost all people wish to avoid getting caught in, save for Power-Armor or Hazmat protected individuals. During a Rad-Storm, people would expect to hide in their homes, or face grave illness later on. 

Let me know any critique you have, I know this is probably a /BIG/ ask. Open to critique and refinement. -Murderfox

**Comment by UndeadNappist** [comment]
Weather's already in, it's just broken. See also #156

**Comment by Kimochiiiiiiiiiiiiii** [comment]
The rad storm can just get copy pasted from a normal ss13 codebase, radiation storms in other space servers are a common thing

**Comment by LetterN** [comment]
this already exists, but the controller is not active

**Comment by LetterN** [comment]
but the issue when you use it, at roundstart it will spawn it
