### ISSUE TITLE
Playable Super Mutants, Ghouls, Robots and Synths. 

### ISSUE THREAD

**Issue by Murderfoxen** [BadDeathclaw/TG-Claw#605]
### Intro:
New playable races are often very asked for. But how can we do it whilst keeping it balanced? Keeping it fun? Without whitelists? Or with them?  Lot's of questions likely go through your brain about the balancing hell of having more than just people! Well, I'm going to try and tackle that. 

**Whitelists, yay or nay?**
Most servers who require whitelists genuinely require systems to moderate who and what. If we want to remain a Immersive server transitioning towards more RP, we can consider it. However, our rules should honestly be enough to prevent grief/trolling where necisarry. I'm personally against Whitelists, but consider the races below for requiring moderation if you feel they are genuinely too powerful. 

### Ghouls:
 Very common in the wastes, especially in the most irradiates places. Many have come to known the feral ghouls, whilst some wear human clothing and cling to their humanity. These ghouls are intriguing characters. Some are ancient -- but most who are, are also insane. Only the brightest members of ghoul society keep their wits, and they are always full of stories as a result. 

**Pros:**
- Stronger than normal people.
- Faster than normal people.
- Resitances to radiation.
- Has claw attacks (slight damage increase unarmed)
- Can become more powerful, at the stake of their humanity.
- Resistance to physical/melee damage, due to a lack of nerves and tough skin. 

**Cons:**
- Very weak to Burn damage. 
- Many people look down upon you and treat you badly due to your horrific looks and pendant for insanity over time. 
- Your skin is leathery and dry, meaning once ignited, it is much harder for you to put yourself out. 
- Laser weaponry is twice as effective, as it is concentrated fire!

**Sub-race:** Glowing one.
**Pro:** 
- Can consume 50 Uranium to evolve into a stronger version. The only thing that increases is their health-pool and claw attack damage during their first 'evolution' - Another 50 uranium sheets results in a Glowing one, capable of healing from radioactivity at a faster rate depending on the levels of radiation and excreting a very small aura of radiation by themselves, allowing them to heal slowly over time. 

**Cons:** 
- Upon 'Glowing One' Status, they leak a weak aura of radiation. It means any who become one, are not welcome within streets near actual people. They may even be hunted, due to their abominable, glowing form. 
- All cons stated for ghouls effect glowing ones. 

### Super-Mutants: The big boys. Unfortunate expirements of the FEV. (Forced evolution virus) 
Super mutants are notoriously strong -- but equally insane and stupid. They have fallen into tribal lifestyles, whilst some have even developed into bandits and scavengers to survive. They are larger than an average human, and have unmissable green, grey, yellow or blue hued skin. They are not welcome within society, and thus, are forced to roam the wastes, make odd allegiances, or face death. That is why the super-mutant is strong. The variant I am statting is based on the **Mariposa** Origin of Super mutant. (New Vegas)

**Pros:** 
- More healthpoints to represent their big builds.
- Physically stronger with Melee weapons, unarmed strikes and Throwing people. 
- You Regenerate health at a fast, if not supernatural rate, due to the FEV. 

**Cons:**
- Brain damage from the start.
- Sterile, but still has 'organs' 
- Talking physically pains you due to your jaw deformation. Almost all words will be in caps and slurred.
- Most people are terrified of you, and will try to kill you on sight. 
- You MUST spawn as a Wastelander or Raider. All other roles are Locked to Supermutants.

### Robots: 
One of my weirder and easier race suggestions, but it's here because it'd be nice to play one from round start.  A lot of people would love to play a wandering Eyebot, protectron, Mr.Handy or who knows what else, from the very start. This entry is easy, as these things are already being implemented and genuinely don't need conceptualizing as a result. Yay!

### Synth's: 
Very rare. Fully cybernetic bodies, created by the enclave. Earlier models look entirely alien, whilst more recent models look very human - to the point they could assimilate a populace if they wanted to. The only way to tell the difference is by making them bleed. 

**Pros:** 
- A welder and wire will fix almost anything, given time. 
- You do not bleed, thus you cannot suffer blood-loss.
- You can hack doors and mechanisms, very slowly. 
- You are more durable than an average human. 
- Potentially upgrade-able, in time. 

**Cons:**
-Susceptibility to burn damage.(electrocution/plastic/synthetic materials being flammable).
-Many people see you as abhorrent and outright will attack you, unless you look human.
-BoS members will likely attempt to steal you. 
-You may only start as a Wastelander, due to your lore. On special rounds, you might be able to spawn as an Enclave member. 

Let me know what you think. New races and balancing issues mean I expect a lot of feedback and suggestions on how we'd balance, code or even implement races in a way to promote Immersive RP. Let me know what you think!

**Comment by OceanMonn** [comment]
Ghouls are already planned. Ren said flat out no to super mutants, robots can already be borgs, and synths would be flat out no

**Comment by RenGusta** [comment]
For context: I said flat out no because it's never worked before and I don't think I can trust the playerbase as is, with their penchant for random genetics 'luck' with something that is dubiously a mutation.

Unless we make it extremely likely to instantly and irreparably kill you.

**Comment by Murderfoxen** [comment]
I have to agree tbh, I wouldn't trust a majority of players having access to these things without being approved. I do however think they would definately add to the Fallout Universe, if considered. 

I think Ren's saying no because Super-mutants exist in TG, but they are op. I'd say the FEV (If you injected it) should legitimately have a 50% chance to ouright kill you. Lorefriendly amirite

**Comment by DIamonnd** [comment]
Look now, maybe not allow the most "IM THE FUKKEN STRONK!" races as outright roundstart, shit maybe whitelisted even, but what I ahd in mind is them to be automated events (as antags are in ss13), so we dont have shithead mc fuck going supermutant and killign every fucking one each round. I believe the addition of these atuo events would be pretty good not only in making each round unique but also bringing stuff some people do want to see in this game, shit like enclave, abudctor aliens, supermutant squads and such would be at the most, re skinned F13 antags, but as in the fallout world everyone and their grandmothers have weapons, it would be a rather new and interesting experience to all.

**Comment by AdamElTablawy** [comment]
You can already use genetics or FEV to give yourself hulk.

Otherwise, all these other races are 'humans, but stronger', and frankly there's not much difference to a powergamer-if they're playing the game to murder people, they'll pick raider and kill people at the drop of the hat. Giving them shit like ghoul or synth as you gave their weaknesses means that people will go ghoul raider or ghoul synth or whatever, and murder people but with advantages in combat.

**Comment by UndeadNappist** [comment]
#594
