### ISSUE TITLE
Abductor Camera Console doesn't work

### ISSUE THREAD

**Issue by ErwinSnowden** [BadDeathclaw/TG-Claw#616]
[Priority]: Low

[PR]: If possible, make it so it doesn't rely on cameras for sight, that should fix it but I have no idea how that will work.

[Reproduction]: If you load up a private session of the code and become an abductor, agent or scientist it really doesn't matter, you will not be able to use any cameras outside of the raider mall and designated areas, which sucks since abductors can only recall subjects there, and the scientist can't check up on the agent to ensure their safety.

[For Admins]: Regular conditions outside of setting yourself as an abductor scientist in the abductor console

[Notes]: I'd recommend limiting it to the "desert" area like xenobiology cams on /tg/code where they can only go around xenobiology. Going inside buildings like the vault and shit would be overpowered and realistically they'd only be able to beam down in an open area. I really want this fixed so we can push forward and see the good not xenomorph aliens as a special event.

**Comment by UndeadNappist** [comment]
I'm not sure ANY cameras work.

**Comment by LetterN** [comment]
consoles only work on areas with cammeras

**Comment by TheHellFireo** [comment]
It's just better to remove the entire abductor console tbh.
