### ISSUE TITLE
Add spam prevention to admin-logging

### ISSUE THREAD

**Issue by UndeadNappist** [BadDeathclaw/TG-Claw#622]
Same thing as what happens in the text box where it has a little x5 number or what have you, only for internal admin logs.
Should read something like
[Beginning Timestamp - End Timestamp] [Event] [Number of times]

**Comment by Kimochiiiiiiiiiiiiii** [comment]
Wouldn't this put many actions, unimpeded by others, fuse in a single instance of time?

**Comment by UndeadNappist** [comment]
Good point. There'd have to be a maximum amount of time for the compression.

**Comment by Kimochiiiiiiiiiiiiii** [comment]
Having even two fused can cause many misinterpretations, issues with ahelps and wrongly placed bans or at worse, a bad player not being banned.

**Comment by Kimochiiiiiiiiiiiiii** [comment]
Sorry lad, you and the other admins will have to endure the pain of some messages spamming your screen for the sake of the well-being of the playerbase, the duration of a standard ahelp, and your time.

**Comment by JohnBigless** [comment]
Speaking of spamming admin-logs, replace the shitty "get-stunned-when-you-pull-out-your-gun" with something less lazy.

**Comment by UndeadNappist** [comment]
Please keep statements on topic. If you wish to open another issue, there is nothing preventing you from doing so. Use precise language as much as possible.
