### ISSUE TITLE
Remove either the ORM or the Furnace

### ISSUE THREAD

**Issue by UndeadNappist** [BadDeathclaw/TG-Claw#623]
They do exactly the same thing only in different ways.

We only need one of them.

Argue about which one you want to keep.

**Comment by UndeadNappist** [comment]
If nobody cares I'm deleting the ORM because the furnace is more interesting.

**Comment by Raze500** [comment]
ORM

**Comment by UndeadNappist** [comment]
Actually leave a reason.

**Comment by Raze500** [comment]
Beacuse is easy(?)....

**Comment by DIamonnd** [comment]
Delete both, grilled bonfire gang

**Comment by JTGSZ** [comment]
I actually like the furnace a lot more too.

**Comment by skateboardjones** [comment]
Shoot the ORM in the head.
