### ISSUE TITLE
Initialize() is not triggering properly for jobstart

### ISSUE THREAD

**Issue by UndeadNappist** [BadDeathclaw/TG-Claw#624]
Not interacting properly with vars or not engaging at all. Spawners have no such issues.

**Comment by rhicora** [comment]
Which pull caused this?

**Comment by UndeadNappist** [comment]
Some checking reveals it's always been an issue, but not many static objects bother calling initialize(). I only noticed it on mine because it hinges on that proc to create derived vars.

If it's on the map it's not an issue either - need to check if it affects latespawns or only initial jobstart spawns.

It does not affect New()

**Comment by UndeadNappist** [comment]
Update: It affects all job spawns. Initialize() doesn't trigger for people who spawn in as jobs with gear on them.
