### ISSUE TITLE
Adminhelp, having a guide to a succesfull ahelp

### ISSUE THREAD

**Issue by improvedname** [BadDeathclaw/TG-Claw#632]
Admin help, explaining how to write a succesfully adminhelp,
then just the usual RDM enter.
something like this

"Please describe your problem concisely and an admin will help as soon as they're able"

then listed in this box
![image](https://user-images.githubusercontent.com/24854897/53200340-9863aa80-3621-11e9-90b8-0e93949de200.png)

**Comment by Kimochiiiiiiiiiiiiii** [comment]
The fuck is this

**Comment by Kimochiiiiiiiiiiiiii** [comment]
Just because someone ahelped furry shit and told you "spank me uwu dadDy" doesn't mean everyone else doesn't know how to properly ahelp.

**Comment by improvedname** [comment]
Being descriptive is the key of helping the admin, and getting your issue solved faster.
just saying RDM won't get you far

**Comment by GhostEcho** [comment]
Lot's of people don't really know how to ahelp with any sort of intent to make a more easy process for the admins investigating, though github really isn't the place for this

**Comment by Raze500** [comment]
Its to hard to understeand!

**Comment by improvedname** [comment]
@raze500 just simple text in the adminhelp box "write your issue as descriptive if you could, admins will get to you as soon they can" it helps the adminhelp progress alot and give people a understanding admins will get to them then just complaining in deadchat for an admin

**Comment by improvedname** [comment]
Have fun with your autistic RDM tickets too.
