### ISSUE TITLE
Add craftable bows

### ISSUE THREAD

**Issue by Raze500** [BadDeathclaw/TG-Claw#640]
- [x] Crafteable bows

- [x] Crafteable crossbows

- [x] Crafteable arrows

- [ ] Adds bows has a ramdom loot(?)

- [ ] Make raze trialcode in the serve lul

**Comment by Kimochiiiiiiiiiiiiii** [comment]
+1 to everything but the last one.

**Comment by improvedname** [comment]
+2 to the last one

**Comment by Raze500** [comment]
The bow code is ready i just need the sprites and know where put them

And also i need make the arrows code.

**Comment by Insanegame27** [comment]
I can try and do some spriting for ya, but I need to know more details regarding theme, mechanics, materials etc. compound, recurve, self? Are there multiple types? What poundage draw weight is being abstractly emulated?

**Comment by Raze500** [comment]
For now i guess would be great a normal bow, from hood and metal... the arrows and a quearry to have the bows.

Some sprites in hand right/left and the proyectile too would be nice.

**Comment by Kimochiiiiiiiiiiiiii** [comment]
There's crossbows already, a map spawns with a vox pirate base that has it

**Comment by Raze500** [comment]
B o w s

**Comment by Kimochiiiiiiiiiiiiii** [comment]
You said crossbows too, fuck off.

**Comment by Raze500** [comment]
I just need some #Nerd Codder monkey will add it has ramdom spawn and some coder mother make me trial coder *SCREAMS IN SPANISH*
