### ISSUE TITLE
Autolathe not Hackable

### ISSUE THREAD

**Issue by Sollessa** [BadDeathclaw/TG-Claw#674]
[Priority]: Low-Medium

[Reproduction]: Autolathe doesn't seem to be able to be hacked.  I attempted to hack it with a toolset implant, identified the wire with the advanced multitool and cut it and nothing.  It's not the only time, I've tried other times and it didn't seem to work.

**Comment by RenGusta** [comment]
Intended functuonality leading up to munitions removal.

**Comment by UndeadNappist** [comment]
You weren't attempting to hack an autolathe.

**Comment by Sollessa** [comment]
Uhhh, yes I was.
