### ISSUE TITLE
¿Adds kids?

### ISSUE THREAD

**Issue by Raze500** [BadDeathclaw/TG-Claw#679]
¿ HMMMMMMMMM Make it a playable race?

**Comment by ErwinSnowden** [comment]
Automatic dwarf mutation for children, less health and melee.
Smaller hitbox with nerfs.
Sounds balanced.
Also remember to make the interact with verb not work on them as a hotfix for child ERP.

**Comment by UndeadNappist** [comment]
18+ plus children = Legal problems.
