### ISSUE TITLE
Molerats have no attack noise

### ISSUE THREAD

**Issue by UndeadNappist** [BadDeathclaw/TG-Claw#683]
Geckos might not either. The stealth killers.

**Comment by skateboardjones** [comment]
Cazadors also don't have an attack noise.

**Comment by UndeadNappist** [comment]
https://github.com/BadDeathclaw/bad-deathclaw/blob/64ba57582479059dd91819603d9ccba356842ca8/code/modules/wasteland/wastelandmob.dm#L23

At least there's one for cazas in the old codebase.

**Comment by ChronicPwnage** [comment]
Here ya go #705
