### ISSUE TITLE
Make slave collars more secure

### ISSUE THREAD

**Issue by Insanegame27** [BadDeathclaw/TG-Claw#686]
As it stands, right now any two random people can, without even the most basic tools, remove a slave collar from each other. This does not make sense ICly, as such an obvious design flaw would be superceded by a physical lock kept by the slave master. 

Slave collars should, when unlocked, function as they are now. A 'Less secure' or 'Incomplete but working' product if one is rushed for time or short on metal or just lazy. When locked, they should only be able to be unlocked by a key holder or a ghetto-surgery-esque operation to pick the lock. Collars should require both tools and help to unlock and remove to dissuade slaves from running or fighting back unless there is a very good chance to escape and be helped. 

I have seen, multiple times, groups of slaves just up and leave the Legion camp after removing each other's collars.

As an aside, these collars should be more visible, so people can tell without examining that someone has one on. Do they even have a worn sprite at the moment?

**Comment by Desuiseiseki** [comment]
It could also send a self signal on tamper so that if all slaves were on the same signal they would shock themselves trying to remove it without outside aid.
Requiring a blanket surgery target + circular saw would be a simple and fairly balanced way to remove a more secure collar.

**Comment by Bodynasr** [comment]
Agreed, slave collars are rather useless.

**Comment by Hekzder** [comment]
Worn sprite is probably a good idea, but requires spriters, which we don't have many of. In terms of making them more secure, that may happen later down the line.
