### ISSUE TITLE
Spawn w/ wrong ammo (NCR Trooper)

### ISSUE THREAD

**Issue by extramrdo** [BadDeathclaw/TG-Claw#687]
[Priority]: # (Is it game breaking? Mostly)

Round: 1170

[Reproduction]: Spawn as Trooper. Have in inventory Remmington, description says Chambered in .308. Unload found from rifle. It's a .308 round. Open backpack. Observe 3 7.62 stripper clips. Try to apply 7.62 stripper clip onto gun. Doesn't load. Remove 1 round from 7.62 stripper clip. It's a 7.62 round. Try to apply it to gun. Doesn't load.

[For Admins]: # (Oddities induced by var-edits and other admin tools are not necessarily bugs. Verify that your issues occur under regular circumstances before reporting them.)

[Notes]: This effectively means Troopers get 5 bullets and their 9mm, plus 3 clips of garbage.

**Comment by JohnOxford** [comment]
//Remington 700
/obj/item/gun/ballistic/shotgun/remington
	name = "Remington 700"
	desc = "A sturdy hunting rifle, chambered in 308. and in use before the war."
	icon_state = "308"
	item_state = "rifle"
	mag_type = /obj/item/ammo_box/magazine/internal/boltaction
	fire_sound = 'sound/f13weapons/hunting_rifle.ogg'
	w_class = WEIGHT_CLASS_BULKY
	weapon_weight = WEAPON_HEAVY

/obj/item/ammo_box/magazine/internal/boltaction
	name = "bolt action rifle internal magazine"
	desc = "Oh god, this shouldn't be here"
	ammo_type = /obj/item/ammo_casing/a762
	caliber = "a762"
	max_ammo = 5
	multiload = 1

/obj/item/ammo_box/a762
	name = "stripper clip (7.62mm)"
	desc = "A stripper clip."
	icon_state = "762"
	ammo_type = /obj/item/ammo_casing/a762
	max_ammo = 5
	multiple_sprites = 1
	materials = list(MAT_METAL = 5000)

.308 and 7.62 are both the same thing, there are no .308 cartridges in the game as far as i know. Recruits spawn with the stripper clips listed above, which i assume is what you were referencing, since troopers spawn with service rifles and magazines.

I'll test this in a bit

**Comment by JTGSZ** [comment]
There are .308 cartridges, ghostecho forgot to change what people spawned with when he split the ammo.

**Comment by JohnOxford** [comment]
datum/outfit/job/ncr/f13recruit
	name = "NCR Recruit"
	jobtype = /datum/job/ncr/f13recruit
	uniform =  		/obj/item/clothing/under/f13/ncr
	suit = 			/obj/item/clothing/suit/armor/f13/ncrarmor
	head = 			/obj/item/clothing/head/f13/ncr
	glasses = 		/obj/item/clothing/glasses/sunglasses/big
	suit_store = 	/obj/item/gun/ballistic/shotgun/remington
	backpack_contents = list(
		/obj/item/ammo_box/a762=3, \

**Comment by JohnOxford** [comment]
recruits spawn with the stripper clips in which the stripper clips have 7.62, which is what the internal magazine accepts which is what the remington uses as a magazine, i dunno why this wouldnt work

**Comment by JohnOxford** [comment]
#693 this fixes it but ideally we'll eventually get around to making it fire 7.62 again
