### ISSUE TITLE
Reworking access levels

### ISSUE THREAD

**Issue by UndeadNappist** [BadDeathclaw/TG-Claw#690]
Right now the access levels have a weird issue with how they're set up. They're designed for the old legacy system and things have been pushed and pulled and new tools added.

Some of these tools are useful to coders and development. Some of them aren't. Some things are just annoying -  like the way coders hear every single adminhelp but basically can't close tickets or do other things, including use Investigate to see past rounds' runtime and spawn logs for bugs.

It's annoying.

Either way, perms and what they give access to needs to be reworked along with rejiggering what all the labels are to be more useful to the server.

I always considered this low priority because it didn't matter that much - everyone's end goal was to see the server be a more fun place.

**Comment by RenGusta** [comment]
I'm willing to be around for any discussion necessary to work this situation out.

**Comment by UndeadNappist** [comment]
#722 
#696
