### ISSUE TITLE
Scarcity II: The Electric Boogaloo

### ISSUE THREAD

**Issue by JohnOxford** [BadDeathclaw/TG-Claw#713]
#653 is the previous issue where some conversation was had on the issue.

A principle concept of a post-apocalyptic game is scarcity of resources, resources are not scarce and this issue will tie into several PR's that will improve upon this concept.
_______________________________________________________________________________
- [ ] Make food scarce
( IN PROGRESS: #712 )
_______________________________________________________________________________
- [ ] Make guns scarce
( SOON™)
_______________________________________________________________________________
- [ ] Make ammo scarce
( SOON™)
- [ ] Make ammo craftable through reloading
( IN PROGRESS: #714 )
- [ ] Make ammo valuable
( SOON™)

_______________________________________________________________________________
- [ ] Make high end medical supplies scarce but offer shittier alternatives in a plentiful way (make healing powder more common place in kits than stimpaks/super stimpaks/drugs
( SOON™)
_______________________________________________________________________________

**Comment by UndeadNappist** [comment]
This has no specific details, reasoning and approach to how to make it both interesting and not overly unpleasant to players, nor does it actually tackle an issue (such as, say, replacing 90% of the autolathes on the map with constructionlathes that cannot print ammo).

#653 already covers that in discussion and in specifics. Not only that, this would be better organized as a PROJECT and not an ISSUE.
