### ISSUE TITLE
Sandbags being deleted [BUG]

### ISSUE THREAD

**Issue by SpiceySpicey** [BadDeathclaw/TG-Claw#727]
Issue reported from  Round ID: 1301 (Bad Deathclaw TG Edition)

Reporting client version: 512

So I'm an NCR trooper gathering up all the cloth around town, I decide to cut it all into cloth (because its like clothing and bedsheets) and make sandbags. I have 2 stacks of cloth. I craft all the bags I can from one stack, then craft all I can from the other. I go to combine the 2 stacks and poof, both stacks combine and then delete themselves.

Relevant logs I have access to:
Mckenzie Blackburn says, "So you're why I can't find cloth"

You discreetly slip the survival knife into the jackboots. Alt-click the jackboots to remove it.

Your cloth stack now contains 50 cloth rolls.

The cloth won't fit in the explorer bag, make some space!

Reed Mclain says, "Yes hahaha"

Mckenzie Blackburn exclaims, "Awesome work man!"

Mckenzie Blackburn says, "Lets make some bags"

Your empty sandbag stack now contains 2 s.

Your empty sandbag stack now contains 3 s.

Your empty sandbag stack now contains 4 s.

Your empty sandbag stack now contains 5 s.

Your empty sandbag stack now contains 6 s.

Your empty sandbag stack now contains 7 s.

Your empty sandbag stack now contains 8 s.

Your empty sandbag stack now contains 9 s.

Your empty sandbag stack now contains 10 s.

Your empty sandbag stack now contains 11 s.

Your empty sandbag stack now contains 12 s.

You haven't got enough the cloth to build empty sandbags!x2

Mckenzie Blackburn has thrown the empty sandbag.

Your empty sandbag stack now contains 2 s.

Your empty sandbag stack now contains 3 s.

Your empty sandbag stack now contains 4 s.

Your empty sandbag stack now contains 5 s.

Your empty sandbag stack now contains 6 s.

Your empty sandbag stack now contains 7 s.

Your empty sandbag stack now contains 8 s.

Your empty sandbag stack now contains 9 s.

Your empty sandbag stack now contains 21 s.

(at this moment they disappear from the floor)

Reed Mclain says, "Lets take them to base first"

Mckenzie Blackburn says, "Wait wait"

Mckenzie Blackburn asks, "Did you just pick them up?"

You put the speed loader (.44) into the explorer bag.

Reed Mclain says, "No"

Mckenzie Blackburn says, "God damnit"

Mckenzie Blackburn says, "The world ate them"

Reed Mclain exclaims, "What !?!?!"

Reed Mclain says, "Fuuuuuuuu"

**Comment by KanohaShinobi** [comment]
actually when I did this, they don't delete themselves. The sprite is bugged and goes missing, likely a fucked up icon state. It's missing a part innit. so will ultimately need to alt click while it's on the ground. the only fix to this... add more sandbags so has the 3 state rather than 2

**Comment by ChronicPwnage** [comment]
Thanks for bringing this to my attention, it's something I missed when I made empty sandbags stackable. I've fixed it in #721
