### ISSUE TITLE
Roll command

### ISSUE THREAD

**Issue by AAIoddysey** [BadDeathclaw/TG-Claw#729]
Please add a /roll command to encourage more slow-paced RP, gunfights, and combat. Make it similar to what they have in HL2RP where it shows a random number and then the other person has to do a /roll and whoever gets the highest number in said action, shot or punch/kick succeeds.

**Comment by companoo** [comment]
no

**Comment by AAIoddysey** [comment]
Why not?

**Comment by ChronicPwnage** [comment]
I don't think this adds anything good to gameplay or is in the style of the server.

**Comment by AAIoddysey** [comment]
So you think that someone coming up to another person and saying "I'm gonna kill you now because you killed my brother" then proceeding to quickly bash there head in with an Axe without giving the other person even a chance to respond is acceptable roleplay?

**Comment by RenGusta** [comment]
I don't think anyone in their right mind would think that,

**Comment by SpiceySpicey** [comment]
I don't think that scenario is even proper escalation?

**Comment by AAIoddysey** [comment]
Well, that's what happens. There was a time where I was playing as a sheriff and I decided to add gun laws and a checkpoint at the den entrance. 

Well while I was processing a person things started to get a bit rowdy and tried to get into the den so I quickly closed the shutters and a couple of minutes later someone tried to open the shutters and I stopped them and well had to open fire on them and please remember that because once they all got in one of them saw they opened fire on someone and this someone happened to be there friend.

So upon seeing that this person was hurt one person said to me "You shot my friend, now you will be dieing." so they Axed away at me without even giving me a chance to respond and I just died.

What I'm trying to get at here is that roleplay is supposed to be slow paced.

**Comment by companoo** [comment]
one good thing about ss13 is the roleplay is mechanical with health and damage and shit, rolls are DOGSHIT and detract from the game

**Comment by JohnOxford** [comment]
i think what this translates too as a suggestion is a more complex accuracy system.

**Comment by UndeadNappist** [comment]
Dice already exist in game as an in-game item, with a RNG attached to it. This serves no purpose.
