### ISSUE TITLE
Change explosions to do damage instead of call qdel directly

### ISSUE THREAD

**Issue by UndeadNappist** [BadDeathclaw/TG-Claw#821]
What it says on the tin. Explosions themselves might be handled by each individual turf itself instead of a thing for explosions themselves.

Game has matured enough it doesn't need to call straight qdel; it can just damage.

Then if we don't want things blowing up we just make them indestructible, easy, and it also means we don't have people gibbing when they get blown up and making admins' jobs harder.

Would allow to fix desert turfs so they stop calling return and canceling out explosions but also make it so they don't get blown up (or, potentially, synching up damage to digging out pits so explosions create holes in the dirt).

**Comment by Light-Weave** [comment]
If it makes explosions actually damage people who aren't standing on the bomb's tile, I'm all for it.

**Comment by LetterN** [comment]
just make explotions not able to devistation
