### ISSUE TITLE
Runtime in null.mind

### ISSUE THREAD

**Issue by UndeadNappist** [BadDeathclaw/TG-Claw#838]
[Priority]: # Low

[PR]: # Mine, having do with moving technophreak away from a quality and into a mind datum.

Basically what's happening is the paperdoll preview and mid-transit results in it calling null because the mob has no mind to attach technophreak to, and similarly, calls null when force-equipping because job code is a pile of junk and so are the equip codes.

Oddly, when I fixed the null call it still worked for the paperdoll preview but __not__ for the transit ; character job would spawn in with no power armor equipped.

Tried various workarounds including for(!mind) and other stuff, and after six hours basically gave up. Good luck out there.

**Comment by LetterN** [comment]
will try to unfuck this

**Comment by UndeadNappist** [comment]
#811 sort of this
