### ISSUE TITLE
Weird noises when moving

### ISSUE THREAD

**Issue by crumplehat** [BadDeathclaw/TG-Claw#844]
Issue reported from  Round ID: 1470 (Bad Deathclaw TG Edition)

Reporting client version: 512

It's weird as hell but I seem to keep hearing pipe banging and creaking noises whenever I walk. I thought it was some kind of weird admin-played music or something, with the notes replaced with sound effects, but when I stopped moving it stopped, and started again when I went moving. I don't know what the deal is with it but I figured I should mention it.

**Comment by GhostEcho** [comment]
Were you wearing bronze greaves or clockwork cult gear? Because Im almost 99.5% certain thats it

**Comment by crumplehat** [comment]
Yes, I just realized that was it, thank you, sorry.
