### ISSUE TITLE
Add faction/faction recruitment

### ISSUE THREAD

**Issue by UndeadNappist** [BadDeathclaw/TG-Claw#859]
Was a feature in the old codebase whereby if you looked at someone it would identify which faction they were in and, further, officers in the faction could recruit people to their faction.

https://github.com/BadDeathclaw/bad-deathclaw

**Comment by RenGusta** [comment]
Could add a Faction Tab for 'Officers' in factions to review, as well as visual icons for those confirmed to be in a faction, to make questioning intruders and easily recognising members easier. Might run into trouble like what we used to have on Drymouth, where people would meta your faction and kill you for association, or people who'd drop out of a faction to be reinvited later, to go undercover. Could go a lot of ways.
