### ISSUE TITLE
Readying Up always fucked, forever, and ever.

### ISSUE THREAD

**Issue by RenGusta** [BadDeathclaw/TG-Claw#874]
[Priority]: # Massive pain in the ass for admins and players

[PR]: # Changing readying up code or something.

[Reproduction]: # Set your prefs, ready up, get random shit.

[For Admins]: # the sweet release of death.

[Notes]: # It's been an issue for a long ass time, and It's never really been formally dragged to the github, and worked on here. I don't know the extent on changing it, but having it only pick from your prefs, and never anything else, is kind of a function of most codebases.

Also remove the ability to even select 'get random job if unavailable', because that's probably the root cause.

**Comment by UndeadNappist** [comment]
I thought I fixed this when I did jobsaving. It probably broke when the jobs were rearranged.
