### ISSUE TITLE
Wearing a gun on your back induces slowdown

### ISSUE THREAD

**Issue by Cactus2388** [BadDeathclaw/TG-Claw#897]
[Priority]: # Fucks up movespeed if you want more than one gun on you

[Reproduction]: # Take out your gun and put it on your backpack slot, this induces slowdown (I've tested with the brush gun and the scoped hunting rifle)

**Comment by pireamaineach** [comment]
The sacrifice is not have a fuckin' backpack.

**Comment by pireamaineach** [comment]
Wait this isn't a P.R.

**Comment by pireamaineach** [comment]
Point still stands I guess, this is dumb.
