### ISSUE TITLE
Den doctor

### ISSUE THREAD

**Issue by TrevinBehrens** [BadDeathclaw/TG-Claw#934]
[Priority]: # (Is it game breaking?) I SPAWNED IN VAULT AS DEN DOCTOR VERY BAD!

Uh?

**Comment by GhostEcho** [comment]
Put it in the other issue

**Comment by pireamaineach** [comment]
I would like elaboration.

**Comment by pireamaineach** [comment]
Oh okay

**Comment by pireamaineach** [comment]
@TrevinBehrens
https://github.com/BadDeathclaw/TG-Claw/issues/933
