### ISSUE TITLE
More Negative Quirks

### ISSUE THREAD

**Issue by PrimeGenerations** [BadDeathclaw/TG-Claw#978]
More negative quirks like:

Alcohol Intolerance (-1)
Addiction to Alcohol (-1)
Addiction to Nicotine (-1)
Addiction to Turbo (-2)
Addiction to Jet (-2)
Insatiable (Gets hungry quickly) (-2)

**Comment by BigManClancy** [comment]
Question, would this Addiction be a curable thing or will it be sort of deep-rooted?

**Comment by Hekzder** [comment]
Messing with the current quirk system rather than revamping it entirely isn't really what we want to do. It's hard to make an inherently broken and bad system work well.
